(function(){var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(b){var f=0;return function(){return f<b.length?{done:!1,value:b[f++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return f?f.call(b):$jscomp.arrayIterator(b)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,f,d){b!=Array.prototype&&b!=Object.prototype&&(b[f]=d.value)};
$jscomp.polyfill=function(b,f,d,a){if(f){d=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var e=b[a];e in d||(d[e]={});d=d[e]}b=b[b.length-1];a=d[b];f=f(a);f!=a&&null!=f&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:f})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function f(){this.batch_=null}function d(a){return a instanceof e?a:new e(function(g,p){g(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;f.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};f.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var a=$jscomp.global.setTimeout;f.prototype.asyncExecuteFunction=function(e){a(e,
0)};f.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var g=0;g<a.length;++g){var e=a[g];a[g]=null;try{e()}catch(y){this.asyncThrow_(y)}}}this.batch_=null};f.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var g=this.createResolveAndReject_();try{a(g.resolve,g.reject)}catch(w){g.reject(w)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(b){e||(e=!0,a.call(g,b))}}var g=this,e=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var g=null!=a;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var g=
void 0;try{g=a.then}catch(w){this.reject_(w);return}"function"==typeof g?this.settleSameAsThenable_(g,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,g){if(0!=this.state_)throw Error("Cannot settle("+a+", "+g+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=g;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
0;a<this.onSettledCallbacks_.length;++a)l.asyncExecute(this.onSettledCallbacks_[a]);this.onSettledCallbacks_=null}};var l=new f;e.prototype.settleSameAsPromise_=function(a){var g=this.createResolveAndReject_();a.callWhenSettled_(g.resolve,g.reject)};e.prototype.settleSameAsThenable_=function(a,g){var e=this.createResolveAndReject_();try{a.call(g,e.resolve,e.reject)}catch(y){e.reject(y)}};e.prototype.then=function(a,g){function b(a,e){return"function"==typeof a?function(e){try{f(a(e))}catch(t){d(t)}}:
e}var f,d,l=new e(function(a,e){f=a;d=e});this.callWhenSettled_(b(a,f),b(g,d));return l};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,e){function g(){switch(b.state_){case 1:a(b.result_);break;case 2:e(b.result_);break;default:throw Error("Unexpected state: "+b.state_);}}var b=this;null==this.onSettledCallbacks_?l.asyncExecute(g):this.onSettledCallbacks_.push(g)};e.resolve=d;e.reject=function(a){return new e(function(e,b){b(a)})};e.race=function(a){return new e(function(e,
b){for(var g=$jscomp.makeIterator(a),f=g.next();!f.done;f=g.next())d(f.value).callWhenSettled_(e,b)})};e.all=function(a){var b=$jscomp.makeIterator(a),f=b.next();return f.done?d([]):new e(function(a,e){function g(e){return function(b){l[e]=b;k--;0==k&&a(l)}}var l=[],k=0;do l.push(void 0),k++,d(f.value).callWhenSettled_(g(l.length-1),e),f=b.next();while(!f.done)})};return e},"es6","es3");
$jscomp.checkStringArgs=function(b,f,d){if(null==b)throw new TypeError("The 'this' value for String.prototype."+d+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+d+" must not be a regular expression");return b+""};
$jscomp.polyfill("String.prototype.endsWith",function(b){return b?b:function(b,d){var a=$jscomp.checkStringArgs(this,b,"endsWith");b+="";void 0===d&&(d=a.length);d=Math.max(0,Math.min(d|0,a.length));for(var e=b.length;0<e&&0<d;)if(a[--d]!=b[--e])return!1;return 0>=e}},"es6","es3");
(function(b){function f(a){if(d[a])return d[a].exports;var e=d[a]={i:a,l:!1,exports:{}};b[a].call(e.exports,e,e.exports,f);e.l=!0;return e.exports}var d={};f.m=b;f.c=d;f.d=function(a,e,b){f.o(a,e)||Object.defineProperty(a,e,{enumerable:!0,get:b})};f.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};f.t=function(a,e){e&1&&(a=f(a));if(e&8||e&4&&"object"===typeof a&&a&&a.__esModule)return a;
var b=Object.create(null);f.r(b);Object.defineProperty(b,"default",{enumerable:!0,value:a});if(e&2&&"string"!=typeof a)for(var d in a)f.d(b,d,function(b){return a[b]}.bind(null,d));return b};f.n=function(a){var b=a&&a.__esModule?function(){return a["default"]}:function(){return a};f.d(b,"a",b);return b};f.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};f.p="/core/office/";return f(f.s=9)})([function(b,f,d){d.d(f,"a",function(){return l});b="undefined"===typeof window?self:window;
var a=b._trnDebugMode||b._trnLogMode,e=b._logFiltersEnabled?b._logFiltersEnabled:{},l=function(b,g){g||(g=b,b="default");a&&e[b]&&console.log("".concat(b,": ").concat(g))}},function(b,f,d){d.d(f,"a",function(){return t});d.d(f,"b",function(){return n});d.d(f,"c",function(){return h});var a=d(0),e=d(7),l="undefined"===typeof window?self:window,p=l.importScripts,g=function(a){if("string"===typeof a){for(var c=new Uint8Array(a.length),b=a.length,x=0;x<b;x++)c[x]=a.charCodeAt(x);return c}return a},w=
function(a){if("string"!==typeof a){for(var c="",b=0,x=a.length,e;b<x;)e=a.subarray(b,b+1024),b+=1024,c+=String.fromCharCode.apply(null,e);return c}return a},y=!1,A=function(a,c){y||(p(l.basePath+"decode.min.js"),y=!0);a=self.BrotliDecode(g(a));return c?a:w(a)};(function(){function a(){this.remainingDataArrays=[]}a.prototype.processRaw=function(a){return a};a.prototype.processBrotli=function(a){this.remainingDataArrays.push(a);return null};a.prototype.GetNextChunk=function(a){this.decodeFunction||
(this.decodeFunction=0===a[0]&&97===a[1]&&115===a[2]&&109===a[3]?this.processRaw:this.processBrotli);return this.decodeFunction(a)};a.prototype.End=function(){if(this.remainingDataArrays.length){for(var a=this.arrays,c=0,b=0;b<a.length;++b)c+=a[b].length;c=new Uint8Array(c);var x=0;for(b=0;b<a.length;++b){var e=a[b];c.set(e,x);x+=e.length}return A(c,!0)}return null};return a})();var v=!1,r=function(a,c){v||(p(l.basePath+"rawinflate.js",l.basePath+"pako_inflate.min.js"),v=!0);var b=10;if("string"===
typeof a){if(a.charCodeAt(3)&8){for(;0!==a.charCodeAt(b);++b);++b}}else if(a[3]&8){for(;0!==a[b];++b);++b}if(c)return a=g(a),a=a.subarray(b,a.length-8),l.pako.inflate(a,{windowBits:-15});a=w(a);a=a.substring(b,a.length-8);return e.a.inflate(a)},k=function(a,b){return b?a:w(a)},m=function(b){var c=!b.shouldOutputArray,e=new XMLHttpRequest;e.open("GET",b.url,b.isAsync);var g=c&&e.overrideMimeType;e.responseType=g?"text":"arraybuffer";g&&e.overrideMimeType("text/plain; charset=x-user-defined");e.send();
var h=function(){var h=Date.now();var f=g?e.responseText:new Uint8Array(e.response);Object(a.a)("worker","Result length is "+f.length);f.length<b.compressedMaximum?(f=b.decompressFunction(f,b.shouldOutputArray),Object(a.a)("worker","Decompressed length is "+f.length),console.warn("There may be some degradation of performance. Your server has not been configured to serve .gz. and .br. files with the expected Content-Encoding. See http://www.pdftron.com/kb_content_encoding for instructions on how to resolve this.")):
c&&(f=w(f));Object(a.a)("worker",b.url+" Decompression took "+(Date.now()-h));return f};if(b.isAsync)var f=new Promise(function(a,c){e.onload=function(){200===this.status?a(h()):c("Download Failed "+b.url)};e.onerror=function(){c("Network error occurred "+b.url)}});else{if(200===e.status)return h();throw Error("Failed to load "+b.url);}return f},t=function(a){var b=a.lastIndexOf("/");-1===b&&(b=0);var c=a.slice(b).replace(".",".br.");return a.slice(0,b)+c},c=function(a,b){var c=a.lastIndexOf("/");
-1===c&&(c=0);var e=a.slice(c).replace(".",".gz.");b.url=a.slice(0,c)+e;b.decompressFunction=r;return m(b)},u=function(a,b){b.url=t(a);b.decompressFunction=A;return m(b)},q=function(a,b){a.endsWith(".js.mem")?a=a.slice(0,-4):a.endsWith(".mem")&&(a=a.slice(0,-4)+".js.mem");b.url=a;b.decompressFunction=k;return m(b)},z=function(a,b,c,e){return a.catch(function(a){console.warn(a);return e(b,c)})},D=function(a,b,c){var e;if(c.isAsync){var f=b[0](a,c);for(e=1;e<b.length;++e)f=z(f,a,c,b[e]);return f}for(e=
0;e<b.length;++e)try{return b[e](a,c)}catch(H){console.warn(H.message)}throw Error("");},h=function(a,b,e,f){return D(a,[c,u,q],{compressedMaximum:b,isAsync:e,shouldOutputArray:f})},n=function(a,b,e,f){return D(a,[u,c,q],{compressedMaximum:b,isAsync:e,shouldOutputArray:f})}},function(b,f,d){d.d(f,"c",function(){return p});d.d(f,"b",function(){return g});d.d(f,"a",function(){return w});var a="undefined"===typeof window?self:window;b=function(){var a=navigator.userAgent.toLowerCase();return(a=/(msie) ([\w.]+)/.exec(a)||
/(trident)(?:.*? rv:([\w.]+)|)/.exec(a))?parseInt(a[2],10):a}();(function(){var b=a.navigator.userAgent.match(/Chrome\/(.*?) /);return b?parseInt(b[1],10):b})();(function(){var b=a.navigator.userAgent.match(/OPR/),e=a.navigator.userAgent.match(/Maxthon/),f=a.navigator.userAgent.match(/Edge/);return a.navigator.userAgent.match(/Chrome\/(.*?) /)&&!b&&!e&&!f})();navigator.userAgent.match(/Edge/i);f=/iPad|iPhone|iPod/.test(a.navigator.platform)||"MacIntel"===navigator.platform&&1<navigator.maxTouchPoints;
var e=/^((?!chrome|android).)*safari/i.test(a.navigator.userAgent)||/^((?!chrome|android).)*$/.test(a.navigator.userAgent)&&f;a.navigator.userAgent.match(/Firefox/);b||/Android|webOS|Touch|IEMobile|Silk/i.test(navigator.userAgent);navigator.userAgent.match(/(iPad|iPhone|iPod)/i);a.navigator.userAgent.indexOf("Android");var l=/Mac OS X 10_13_6.*\(KHTML, like Gecko\)$/.test(a.navigator.userAgent),p=function(){return e||l},g=!(!self.WebAssembly||!self.WebAssembly.validate),w=-1<a.navigator.userAgent.indexOf("Edge/16")||
-1<a.navigator.userAgent.indexOf("MSAppHost")},function(b,f){f=function(){return this}();try{f=f||(new Function("return this"))()}catch(d){"object"===typeof window&&(f=window)}b.exports=f},function(b,f,d){f.a=function(){ArrayBuffer.prototype.slice||(ArrayBuffer.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.byteLength);a=Math.floor(a);b=Math.floor(b);0>a&&(a+=this.byteLength);0>b&&(b+=this.byteLength);a=Math.min(Math.max(0,a),this.byteLength);b=Math.min(Math.max(0,b),this.byteLength);
if(0>=b-a)return new ArrayBuffer(0);var e=new ArrayBuffer(b-a),f=new Uint8Array(e);a=new Uint8Array(this,a,b-a);f.set(a);return e})}},function(b,f,d){d.d(f,"a",function(){return w});var a=d(6),e=d(1),l=d(8),p=d(2);b="undefined"===typeof window?self:window;b.Uint8ClampedArray||(b.Uint8ClampedArray=b.Uint8Array);"undefined"===typeof b.crypto&&(b.crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()}});var g=function(a){var b=this;this.promise=a.then(function(a){b.response=
a;b.status=200})};g.prototype={addEventListener:function(a,b){this.promise.then(b)}};var w=function(b,f,d){if(!p.b||p.a||Object(p.c)()||d){d=Object(e.b)("".concat((Module.asmjsPrefix?Module.asmjsPrefix:"")+b,".js.mem"),f[".js.mem"],!1);var w=Object(e.c)("".concat((Module.memoryInitializerPrefixURL?Module.memoryInitializerPrefixURL:"")+b,".mem"),f[".mem"],!0,!0);Module.memoryInitializerRequest=new g(w)}else Module.instantiateWasm=function(e,g){return Object(l.a)(Object(a.a)(),"".concat(b,"Wasm.wasm"),
e,f["Wasm.wasm"]).then(function(a){g(a)})},d=Object(e.b)("".concat(b,"Wasm.js.mem"),f["Wasm.js.mem"],!1,!1);d=new Blob([d],{type:"application/javascript"});importScripts(URL.createObjectURL(d))}},function(b,f,d){function a(){return e}d.d(f,"a",function(){return a});var e=34},function(b,f,d){var a=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],e=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],l=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,
3,4,4,4,4,5,5,5,5,0,99,99],p=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],g=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],w=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],y=function(){this.list=this.next=null},A=function(){this.n=this.b=this.e=0;this.t=null},v=function(a,b,e,c,f,g){this.BMAX=16;this.N_MAX=288;this.status=0;this.root=null;this.m=0;var d=Array(this.BMAX+1),u,h,n,x=Array(this.BMAX+1),q,k=new A,
l=Array(this.BMAX);var m=Array(this.N_MAX);var t=Array(this.BMAX+1),F,E;var w=this.root=null;for(h=0;h<d.length;h++)d[h]=0;for(h=0;h<x.length;h++)x[h]=0;for(h=0;h<l.length;h++)l[h]=null;for(h=0;h<m.length;h++)m[h]=0;for(h=0;h<t.length;h++)t[h]=0;var v=256<b?a[256]:this.BMAX;var B=a;var p=0;h=b;do d[B[p]]++,p++;while(0<--h);if(d[0]==b)this.root=null,this.status=this.m=0;else{for(n=1;n<=this.BMAX&&0==d[n];n++);var r=n;g<n&&(g=n);for(h=this.BMAX;0!=h&&0==d[h];h--);var I=h;g>h&&(g=h);for(F=1<<n;n<h;n++,
F<<=1)if(0>(F-=d[n])){this.status=2;this.m=g;return}if(0>(F-=d[h]))this.status=2,this.m=g;else{d[h]+=F;t[1]=n=0;B=d;p=1;for(q=2;0<--h;)t[q++]=n+=B[p++];B=a;h=p=0;do 0!=(n=B[p++])&&(m[t[n]++]=h);while(++h<b);b=t[I];t[0]=h=0;B=m;p=0;m=-1;var C=x[0]=0;q=null;for(E=0;r<=I;r++)for(a=d[r];0<a--;){for(;r>C+x[1+m];){C+=x[1+m];m++;E=(E=I-C)>g?g:E;if((u=1<<(n=r-C))>a+1)for(u-=a+1,q=r;++n<E&&!((u<<=1)<=d[++q]);)u-=d[q];C+n>v&&C<v&&(n=v-C);E=1<<n;x[1+m]=n;q=Array(E);for(u=0;u<E;u++)q[u]=new A;w=null==w?this.root=
new y:w.next=new y;w.next=null;w.list=q;l[m]=q;0<m&&(t[m]=h,k.b=x[m],k.e=16+n,k.t=q,n=(h&(1<<C)-1)>>C-x[m],l[m-1][n].e=k.e,l[m-1][n].b=k.b,l[m-1][n].n=k.n,l[m-1][n].t=k.t)}k.b=r-C;p>=b?k.e=99:B[p]<e?(k.e=256>B[p]?16:15,k.n=B[p++]):(k.e=f[B[p]-e],k.n=c[B[p++]-e]);u=1<<r-C;for(n=h>>C;n<E;n+=u)q[n].e=k.e,q[n].b=k.b,q[n].n=k.n,q[n].t=k.t;for(n=1<<r-1;0!=(h&n);n>>=1)h^=n;for(h^=n;(h&(1<<C)-1)!=t[m];)C-=x[m],m--}this.m=x[1];this.status=0!=F&&1!=I?1:0}}},r={Stream:function(a){this.zip_inflate_start();this.zip_inflate_data=
a;this.zip_inflate_pos=0}};r.Stream.prototype={getBytes:function(a){for(var b,e=Array(1024),c=[],f=0;f<a&&0<(b=this.zip_inflate_internal(e,0,e.length));)c[c.length]=String.fromCharCode.apply(null,e.slice(0,b)),f+=b;return f?(this.zip_inflate_data=this.zip_inflate_data.slice(this.zip_inflate_pos),this.zip_inflate_pos=0,c.join("")):""},zip_GET_BYTE:function(){return this.zip_inflate_data.length==this.zip_inflate_pos?-1:this.zip_inflate_data.charCodeAt(this.zip_inflate_pos++)&255},zip_NEEDBITS:function(a){for(;this.zip_bit_len<
a;)this.zip_bit_buf|=this.zip_GET_BYTE()<<this.zip_bit_len,this.zip_bit_len+=8},zip_GETBITS:function(b){return this.zip_bit_buf&a[b]},zip_DUMPBITS:function(a){this.zip_bit_buf>>=a;this.zip_bit_len-=a},zip_inflate_codes:function(a,b,e){var c,f;if(0==e)return 0;for(f=0;;){this.zip_NEEDBITS(this.zip_bl);var g=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];for(c=g.e;16<c;){if(99==c)return-1;this.zip_DUMPBITS(g.b);c-=16;this.zip_NEEDBITS(c);g=g.t[this.zip_GETBITS(c)];c=g.e}this.zip_DUMPBITS(g.b);if(16==
c)this.zip_wp&=32767,a[b+f++]=this.zip_slide[this.zip_wp++]=g.n;else{if(15==c)break;this.zip_NEEDBITS(c);this.zip_copy_leng=g.n+this.zip_GETBITS(c);this.zip_DUMPBITS(c);this.zip_NEEDBITS(this.zip_bd);g=this.zip_td.list[this.zip_GETBITS(this.zip_bd)];for(c=g.e;16<c;){if(99==c)return-1;this.zip_DUMPBITS(g.b);c-=16;this.zip_NEEDBITS(c);g=g.t[this.zip_GETBITS(c)];c=g.e}this.zip_DUMPBITS(g.b);this.zip_NEEDBITS(c);this.zip_copy_dist=this.zip_wp-g.n-this.zip_GETBITS(c);for(this.zip_DUMPBITS(c);0<this.zip_copy_leng&&
f<e;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=32767,a[b+f++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++]}if(f==e)return e}this.zip_method=-1;return f},zip_inflate_stored:function(a,b,e){var c=this.zip_bit_len&7;this.zip_DUMPBITS(c);this.zip_NEEDBITS(16);c=this.zip_GETBITS(16);this.zip_DUMPBITS(16);this.zip_NEEDBITS(16);if(c!=(~this.zip_bit_buf&65535))return-1;this.zip_DUMPBITS(16);this.zip_copy_leng=c;for(c=0;0<this.zip_copy_leng&&c<e;)this.zip_copy_leng--,
this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+c++]=this.zip_slide[this.zip_wp++]=this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1);return c},zip_inflate_fixed:function(a,b,f){if(null==this.zip_fixed_tl){var c,d=Array(288);for(c=0;144>c;c++)d[c]=8;for(;256>c;c++)d[c]=9;for(;280>c;c++)d[c]=7;for(;288>c;c++)d[c]=8;this.zip_fixed_bl=7;c=new v(d,288,257,e,l,this.zip_fixed_bl);if(0!=c.status)return alert("HufBuild error: ".concat(c.status)),-1;this.zip_fixed_tl=c.root;this.zip_fixed_bl=
c.m;for(c=0;30>c;c++)d[c]=5;this.zip_fixed_bd=5;c=new v(d,30,0,p,g,this.zip_fixed_bd);if(1<c.status)return this.zip_fixed_tl=null,alert("HufBuild error: ".concat(c.status)),-1;this.zip_fixed_td=c.root;this.zip_fixed_bd=c.m}this.zip_tl=this.zip_fixed_tl;this.zip_td=this.zip_fixed_td;this.zip_bl=this.zip_fixed_bl;this.zip_bd=this.zip_fixed_bd;return this.zip_inflate_codes(a,b,f)},zip_inflate_dynamic:function(a,b,f){var c,d,m,k=Array(316);for(c=0;c<k.length;c++)k[c]=0;this.zip_NEEDBITS(5);var t=257+
this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(5);var h=1+this.zip_GETBITS(5);this.zip_DUMPBITS(5);this.zip_NEEDBITS(4);c=4+this.zip_GETBITS(4);this.zip_DUMPBITS(4);if(286<t||30<h)return-1;for(d=0;d<c;d++)this.zip_NEEDBITS(3),k[w[d]]=this.zip_GETBITS(3),this.zip_DUMPBITS(3);for(;19>d;d++)k[w[d]]=0;this.zip_bl=7;d=new v(k,19,19,null,null,this.zip_bl);if(0!=d.status)return-1;this.zip_tl=d.root;this.zip_bl=d.m;var n=t+h;for(c=m=0;c<n;){this.zip_NEEDBITS(this.zip_bl);var x=this.zip_tl.list[this.zip_GETBITS(this.zip_bl)];
d=x.b;this.zip_DUMPBITS(d);d=x.n;if(16>d)k[c++]=m=d;else if(16==d){this.zip_NEEDBITS(2);d=3+this.zip_GETBITS(2);this.zip_DUMPBITS(2);if(c+d>n)return-1;for(;0<d--;)k[c++]=m}else{17==d?(this.zip_NEEDBITS(3),d=3+this.zip_GETBITS(3),this.zip_DUMPBITS(3)):(this.zip_NEEDBITS(7),d=11+this.zip_GETBITS(7),this.zip_DUMPBITS(7));if(c+d>n)return-1;for(;0<d--;)k[c++]=0;m=0}}this.zip_bl=9;d=new v(k,t,257,e,l,this.zip_bl);0==this.zip_bl&&(d.status=1);if(0!=d.status)return-1;this.zip_tl=d.root;this.zip_bl=d.m;for(c=
0;c<h;c++)k[c]=k[c+t];this.zip_bd=6;d=new v(k,h,0,p,g,this.zip_bd);this.zip_td=d.root;this.zip_bd=d.m;return 0==this.zip_bd&&257<t||0!=d.status?-1:this.zip_inflate_codes(a,b,f)},zip_inflate_start:function(){null==this.zip_slide&&(this.zip_slide=Array(65536));this.zip_bit_len=this.zip_bit_buf=this.zip_wp=0;this.zip_method=-1;this.zip_eof=!1;this.zip_copy_leng=this.zip_copy_dist=0;this.zip_fixed_tl=this.zip_tl=null},zip_inflate_internal:function(a,b,e){var c;for(c=0;c<e&&(!this.zip_eof||-1!=this.zip_method);){if(0<
this.zip_copy_leng){if(0!=this.zip_method)for(;0<this.zip_copy_leng&&c<e;)this.zip_copy_leng--,this.zip_copy_dist&=32767,this.zip_wp&=32767,a[b+c++]=this.zip_slide[this.zip_wp++]=this.zip_slide[this.zip_copy_dist++];else{for(;0<this.zip_copy_leng&&c<e;)this.zip_copy_leng--,this.zip_wp&=32767,this.zip_NEEDBITS(8),a[b+c++]=this.zip_slide[this.zip_wp++]=this.zip_GETBITS(8),this.zip_DUMPBITS(8);0==this.zip_copy_leng&&(this.zip_method=-1)}if(c==e)break}if(-1==this.zip_method){if(this.zip_eof)break;this.zip_NEEDBITS(1);
0!=this.zip_GETBITS(1)&&(this.zip_eof=!0);this.zip_DUMPBITS(1);this.zip_NEEDBITS(2);this.zip_method=this.zip_GETBITS(2);this.zip_DUMPBITS(2);this.zip_tl=null;this.zip_copy_leng=0}switch(this.zip_method){case 0:var d=this.zip_inflate_stored(a,b+c,e-c);break;case 1:d=null!=this.zip_tl?this.zip_inflate_codes(a,b+c,e-c):this.zip_inflate_fixed(a,b+c,e-c);break;case 2:d=null!=this.zip_tl?this.zip_inflate_codes(a,b+c,e-c):this.zip_inflate_dynamic(a,b+c,e-c);break;default:d=-1}if(-1==d)return this.zip_eof?
0:-1;c+=d}return c}};r.inflate=function(a){return(new r.Stream(a)).getBytes(4E9)};f.a=r},function(b,f,d){function a(a){return new Promise(function(b,e){var d=indexedDB.open(w,a);d.onerror=e.bind(null,"Error opening wasm cache database");d.onsuccess=function(){b(d.result)};d.onupgradeneeded=function(a){var b=d.result;b.objectStoreNames.contains(y)&&(console.log("Clearing out version ".concat(a.oldVersion," wasm cache")),b.deleteObjectStore(y));console.log("Creating version ".concat(a.newVersion," wasm cache"));
b.createObjectStore(y)}})}function e(a,b){return new Promise(function(e,d){var f=a.transaction([y]).objectStore(y).get(b);f.onsuccess=function(a){f.result?e(f.result):d("Module ".concat(b," was not found in wasm cache"))};f.onerror=d.bind(null,"Error getting wasm module ".concat(b))})}function l(b,d,f,l){function w(a,b){a=a.transaction([y],"readwrite").objectStore(y).put(b,d);a.onerror=function(a){console.log("Failed to store in wasm cache: ".concat(a))};a.onsuccess=function(a){console.log("Successfully stored ".concat(d,
" in wasm cache"))}}function k(a){u=u||Date.now();return a?(Object(p.a)("load","Try instantiateStreaming"),fetch(Object(g.a)(d)).then(function(a){return WebAssembly.instantiateStreaming(a,f)})["catch"](function(a){Object(p.a)("load","instantiateStreaming Failed ".concat(d," message ").concat(a.message));return k(!1)})):Object(g.b)(d,l,!0,!0).then(function(a){c=Date.now();Object(p.a)("load","Request took ".concat(c-u," ms"));return WebAssembly.instantiate(a,f)})}var c,u;return a(b).then(function(a){return e(a,
d).then(function(a){Object(p.a)("Found ".concat(d," in wasm cache"));return WebAssembly.instantiate(a,f)},function(b){Object(p.a)(b);return k(!!WebAssembly.instantiateStreaming).then(function(b){try{Object(p.a)("load","WASM compilation took ".concat(Date.now()-(c||u)," ms")),w(a,b.module)}catch(h){}return b.instance})})},function(a){console.log(a);return k().then(function(a){return a.instance})})}d.d(f,"a",function(){return l});var p=d(0),g=d(1),w="wasm-cache",y="wasm-cache"},function(b,f,d){b.exports=
d(10)},function(b,f,d){d.r(f);d(11);b=d(4);d(16);Object(b.a)()},function(b,f,d){(function(a,b){function e(a){"@babel/helpers - typeof";e="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return e(a)}(function(a){function f(){for(var a=0;a<G.length;a++)G[a][0](G[a][1]);G=[];H=!1}function l(a,b){G.push([a,b]);H||(H=!0,L(f,0))}function p(a,b){function c(a){r(b,
a)}function e(a){m(b,a)}try{a(c,e)}catch(B){e(B)}}function A(a){var b=a.owner,c=b.state_;b=b.data_;var e=a[c];a=a.then;if("function"===typeof e){c=x;try{b=e(b)}catch(B){m(a,B)}}v(a,b)||(c===x&&r(a,b),c===J&&m(a,b))}function v(a,b){var c;try{if(a===b)throw new TypeError("A promises callback cannot return that same promise.");if(b&&("function"===typeof b||"object"===e(b))){var d=b.then;if("function"===typeof d)return d.call(b,function(e){c||(c=!0,b!==e?r(a,e):k(a,e))},function(b){c||(c=!0,m(a,b))}),
!0}}catch(B){return c||m(a,B),!0}return!1}function r(a,b){a!==b&&v(a,b)||k(a,b)}function k(a,b){a.state_===h&&(a.state_=n,a.data_=b,l(c,a))}function m(a,b){a.state_===h&&(a.state_=n,a.data_=b,l(u,a))}function t(a){var b=a.then_;a.then_=void 0;for(a=0;a<b.length;a++)A(b[a])}function c(a){a.state_=x;t(a)}function u(a){a.state_=J;t(a)}function q(a){if("function"!==typeof a)throw new TypeError("Promise constructor takes a function argument");if(!1===this instanceof q)throw new TypeError("Failed to construct 'Promise': Please use the 'new' operator, this object constructor cannot be called as a function.");
this.then_=[];p(a,this)}a.createPromiseCapability=function(){var a={},b=new q(function(b,c){a.resolve=b;a.reject=c});a.promise=b;return a};var z=a.Promise,D=z&&"resolve"in z&&"reject"in z&&"all"in z&&"race"in z&&function(){var a;new z(function(b){a=b});return"function"===typeof a}();"undefined"!==typeof exports&&exports?(exports.Promise=D?z:q,exports.Polyfill=q):"function"===typeof define&&d(15)?define(function(){return D?z:q}):D||(a.Promise=q);var h="pending",n="sealed",x="fulfilled",J="rejected",
K=function(){},L="undefined"!==typeof b?b:setTimeout,G=[],H;q.prototype={constructor:q,state_:h,then_:null,data_:void 0,then:function(a,b){a={owner:this,then:new this.constructor(K),fulfilled:a,rejected:b};this.state_===x||this.state_===J?l(A,a):this.then_.push(a);return a.then},"catch":function(a){return this.then(null,a)}};q.all=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.all().");return new this(function(b,c){function e(a){f++;
return function(c){d[a]=c;--f||b(d)}}for(var d=[],f=0,g=0,h;g<a.length;g++)(h=a[g])&&"function"===typeof h.then?h.then(e(g),c):d[g]=h;f||b(d)})};q.race=function(a){if("[object Array]"!==Object.prototype.toString.call(a))throw new TypeError("You must pass an array to Promise.race().");return new this(function(b,c){for(var e=0,d;e<a.length;e++)(d=a[e])&&"function"===typeof d.then?d.then(b,c):b(d)})};q.resolve=function(a){return a&&"object"===e(a)&&a.constructor===this?a:new this(function(b){b(a)})};
q.reject=function(a){return new this(function(b,c){c(a)})}})("undefined"!==typeof window?window:"undefined"!==typeof a?a:"undefined"!==typeof self?self:void 0)}).call(this,d(3),d(12).setImmediate)},function(b,f,d){(function(a){function b(a,b){this._id=a;this._clearFn=b}var l="undefined"!==typeof a&&a||"undefined"!==typeof self&&self||window,p=Function.prototype.apply;f.setTimeout=function(){return new b(p.call(setTimeout,l,arguments),clearTimeout)};f.setInterval=function(){return new b(p.call(setInterval,
l,arguments),clearInterval)};f.clearTimeout=f.clearInterval=function(a){a&&a.close()};b.prototype.unref=b.prototype.ref=function(){};b.prototype.close=function(){this._clearFn.call(l,this._id)};f.enroll=function(a,b){clearTimeout(a._idleTimeoutId);a._idleTimeout=b};f.unenroll=function(a){clearTimeout(a._idleTimeoutId);a._idleTimeout=-1};f._unrefActive=f.active=function(a){clearTimeout(a._idleTimeoutId);var b=a._idleTimeout;0<=b&&(a._idleTimeoutId=setTimeout(function(){a._onTimeout&&a._onTimeout()},
b))};d(13);f.setImmediate="undefined"!==typeof self&&self.setImmediate||"undefined"!==typeof a&&a.setImmediate||this&&this.setImmediate;f.clearImmediate="undefined"!==typeof self&&self.clearImmediate||"undefined"!==typeof a&&a.clearImmediate||this&&this.clearImmediate}).call(this,d(3))},function(b,f,d){(function(a,b){(function(a,d){function e(a){delete c[a]}function f(a){if(u)setTimeout(f,0,a);else{var b=c[a];if(b){u=!0;try{var g=b.callback,h=b.args;switch(h.length){case 0:g();break;case 1:g(h[0]);
break;case 2:g(h[0],h[1]);break;case 3:g(h[0],h[1],h[2]);break;default:g.apply(d,h)}}finally{e(a),u=!1}}}}function l(){z=function(a){b.nextTick(function(){f(a)})}}function p(){if(a.postMessage&&!a.importScripts){var b=!0,c=a.onmessage;a.onmessage=function(){b=!1};a.postMessage("","*");a.onmessage=c;return b}}function v(){var b="setImmediate$"+Math.random()+"$",c=function(c){c.source===a&&"string"===typeof c.data&&0===c.data.indexOf(b)&&f(+c.data.slice(b.length))};a.addEventListener?a.addEventListener("message",
c,!1):a.attachEvent("onmessage",c);z=function(c){a.postMessage(b+c,"*")}}function r(){var a=new MessageChannel;a.port1.onmessage=function(a){f(a.data)};z=function(b){a.port2.postMessage(b)}}function k(){var a=q.documentElement;z=function(b){var c=q.createElement("script");c.onreadystatechange=function(){f(b);c.onreadystatechange=null;a.removeChild(c);c=null};a.appendChild(c)}}function m(){z=function(a){setTimeout(f,0,a)}}if(!a.setImmediate){var t=1,c={},u=!1,q=a.document,z,D=Object.getPrototypeOf&&
Object.getPrototypeOf(a);D=D&&D.setTimeout?D:a;"[object process]"==={}.toString.call(a.process)?l():p()?v():a.MessageChannel?r():q&&"onreadystatechange"in q.createElement("script")?k():m();D.setImmediate=function(a){"function"!==typeof a&&(a=new Function(""+a));for(var b=Array(arguments.length-1),d=0;d<b.length;d++)b[d]=arguments[d+1];c[t]={callback:a,args:b};z(t);return t++};D.clearImmediate=e}})("undefined"===typeof self?"undefined"===typeof a?this:a:self)}).call(this,d(3),d(14))},function(b,f){function d(){throw Error("setTimeout has not been defined");
}function a(){throw Error("clearTimeout has not been defined");}function e(a){if(A===setTimeout)return setTimeout(a,0);if((A===d||!A)&&setTimeout)return A=setTimeout,setTimeout(a,0);try{return A(a,0)}catch(u){try{return A.call(null,a,0)}catch(q){return A.call(this,a,0)}}}function l(b){if(v===clearTimeout)return clearTimeout(b);if((v===a||!v)&&clearTimeout)return v=clearTimeout,clearTimeout(b);try{return v(b)}catch(u){try{return v.call(null,b)}catch(q){return v.call(this,b)}}}function p(){k&&m&&(k=
!1,m.length?r=m.concat(r):t=-1,r.length&&g())}function g(){if(!k){var a=e(p);k=!0;for(var b=r.length;b;){m=r;for(r=[];++t<b;)m&&m[t].run();t=-1;b=r.length}m=null;k=!1;l(a)}}function w(a,b){this.fun=a;this.array=b}function y(){}b=b.exports={};try{var A="function"===typeof setTimeout?setTimeout:d}catch(c){A=d}try{var v="function"===typeof clearTimeout?clearTimeout:a}catch(c){v=a}var r=[],k=!1,m,t=-1;b.nextTick=function(a){var b=Array(arguments.length-1);if(1<arguments.length)for(var c=1;c<arguments.length;c++)b[c-
1]=arguments[c];r.push(new w(a,b));1!==r.length||k||e(g)};w.prototype.run=function(){this.fun.apply(null,this.array)};b.title="browser";b.browser=!0;b.env={};b.argv=[];b.version="";b.versions={};b.on=y;b.addListener=y;b.once=y;b.off=y;b.removeListener=y;b.removeAllListeners=y;b.emit=y;b.prependListener=y;b.prependOnceListener=y;b.listeners=function(a){return[]};b.binding=function(a){throw Error("process.binding is not supported");};b.cwd=function(){return"/"};b.chdir=function(a){throw Error("process.chdir is not supported");
};b.umask=function(){return 0}},function(b,f){b.exports={}},function(b,f,d){function a(b){"@babel/helpers - typeof";a="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return a(b)}var e=d(0),l=d(5),p=null;(function(b){function d(){v=function(){}}function f(b){var c=[];return{resource_array:c,msg:JSON.stringify(b.data,function(b,d){if("object"===
a(d)&&(b=null,d instanceof Uint8Array?b=d:d instanceof ArrayBuffer&&(b=new Uint8Array(d)),b)){d=k(b.length);var e=m(d);e&&(new Uint8Array(Module.HEAPU8.buffer,e,b.length)).set(b);c.push(d);return{__trn_res_id:d}}return d})}}function g(a){a=f(a);r(a.msg)}var v,r,k,m;b.basePath="../";var t=b.officeWorkerPath||"";b.workerBasePath&&(b.basePath=b.workerBasePath);var c=function(a){var b={};decodeURIComponent(a.slice(1)).split("&").forEach(function(a){a=a.split("=",2);b[a[0]]=a[1]});return b}(b.location.search);
b.basePath=c.externalPath?c.externalPath:b.basePath+"external/";importScripts("".concat(b.basePath,"Promise.js"));var u=[];onmessage=function(a){u||(u=[]);u.push(a)};b.ContinueFunc=function(a){v("ContinueFunc called");setTimeout(function(){onmessage({data:{action:"continue"}})},a)};if(c.pdfWorkerPath)var q=c.pdfWorkerPath;if(c.officeAsmPath)var z=c.officeAsmPath;b.Module={memoryInitializerPrefixURL:q,asmjsPrefix:z,onRuntimeInitialized:function(){v||d();var a=Date.now()-p;Object(e.a)("load","time duration from start to ready: ".concat(JSON.stringify(a)));
r=function(a){if(null!==a&&void 0!==a&&0!==a){var b=(a.length<<2)+1,c=Module._malloc(b);0<Module.stringToUTF8(a,c,b)&&Module._TRN_OnMessage(c)}};k=function(a){return Module._TRN_CreateBufferResource(a)};m=function(a){return Module._TRN_GetResourcePointer(a)};v("OnReady called");onmessage=g;Module._TRN_InitWorker();for(a=0;a<u.length;++a)onmessage(u[a]);u=null},fetchSelf:function(){p=Date.now();Object(l.a)("".concat(t,"WebOfficeWorker"),{"Wasm.wasm":5E6,"Wasm.js.mem":1E5,".js.mem":5E6,".mem":3E6},
!!navigator.userAgent.match(/Edge/i))},noExitRuntime:!0};b.Module.fetchSelf()})("undefined"===typeof window?self:window)}]);}).call(this || window)
