/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[1],{261:function(le,db,b){b.r(db);var y=b(0);b.n(y);var w=b(22),n=b(8),ke=b(4),z=b(66);db["default"]=function(b){function e(a){var b=[];for(a.wa();a.advance();){var e=a.Ea();"field"===e?b.push(String(a.V("name"))):console.warn("unrecognised field list element: "+e)}a.Na();return b}function h(a,b){return b?"false"===a?!1:!0:"true"===a?!0:!1}function x(a,b){var f=a.Ea();switch(f){case "javascript":return{name:"JavaScript",javascript:a.current.textContent};
case "uri":return{name:"URI",uri:a.V("uri")};case "goto":f=null;a.wa();if(a.advance()){var r=a.V("fit");f={page:a.V("page"),fit:r};if("0"===f.page)console.warn("null page encountered in dest");else switch(b=b(Number(f.page)),r){case "Fit":case "FitB":break;case "FitH":case "FitBH":f.top=b.ha({x:0,y:a.V("top")||0}).y;break;case "FitV":case "FitBV":f.left=b.ha({x:a.V("left")||0,y:0}).x;break;case "FitR":r=b.ha({x:a.V("left")||0,y:a.V("top")||0});b=b.ha({x:a.V("right")||0,y:a.V("bottom")||0});b=new n.a(r.x,
r.y,b.x,b.y);f.top=b.aa;f.left=b.da;f.bottom=b.ba;f.right=b.ga;break;case "XYZ":r=b.ha({x:a.V("left")||0,y:a.V("top")||0});f.top=r.y;f.left=r.x;f.zoom=a.V("zoom")||0;break;default:console.warn("unknown dest fit: "+r)}f={name:"GoTo",dest:f}}else console.GZ("missing dest in GoTo action");a.Na();return f;case "submit-form":f={name:"SubmitForm",url:a.V("url"),format:a.V("format"),method:a.V("method")||"POST",exclude:h(a.V("exclude"),!1)};b=a.V("flags");f.flags=b?b.split(" "):[];for(a.wa();a.advance();)switch(b=
a.Ea(),b){case "fields":f.fields=e(a);break;default:console.warn("unrecognised submit-form child: "+b)}a.Na();return f;case "reset-form":f={name:"ResetForm",exclude:h(a.V("exclude"),!1)};for(a.wa();a.advance();)switch(b=a.Ea(),b){case "fields":f.fields=e(a);break;default:console.warn("unrecognised reset-form child: "+b)}a.Na();return f;case "hide":f={name:"Hide",hide:h(a.V("hide"),!0)};for(a.wa();a.advance();)switch(b=a.Ea(),b){case "fields":f.fields=e(a);break;default:console.warn("unrecognised hide child: "+
b)}a.Na();return f;case "named":return{name:"Named",action:a.V("name")};default:console.warn("Encountered unexpected action type: "+f)}return null}function db(a,b,e){var f={};for(a.wa();a.advance();){var h=a.Ea();switch(h){case "action":h=a.V("trigger");if(b?-1!==b.indexOf(h):1){f[h]=[];for(a.wa();a.advance();){var n=x(a,e);Object(y.isNull)(n)||f[h].push(n)}a.Na()}else console.warn("encountered unexpected trigger on field: "+h);break;default:console.warn("encountered unknown action child: "+h)}}a.Na();
return f}function f(a){return"calculation-order"===a.Ea()?e(a):[]}function a(a){return new ke.a(a.V("r")||0,a.V("g")||0,a.V("b")||0,a.V("a")||1)}function le(b,e){var f=b.V("name"),h=b.V("type")||"Type1",n=b.V("size"),r=e.ha({x:0,y:0});n=e.ha({x:Number(n),y:0});e=r.x-n.x;r=r.y-n.y;f={name:f,type:h,size:Math.sqrt(e*e+r*r)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(b.wa();b.advance();)switch(h=b.Ea(),h){case "stroke-color":f.strokeColor=a(b);break;case "fill-color":f.fillColor=a(b);break;default:console.warn("unrecognised font child: "+
h)}b.Na();return f}function oe(b,e){var f={border:{style:"Solid",width:1},backgroundColor:[],fieldName:b.V("field"),page:b.V("page"),index:b.V("index")||0,rotation:b.V("rotation")||0,flags:[]},h=b.V("appearance");h&&(f.appearance=h);(h=b.V("flags"))&&(f.flags=h.split(" "));for(b.wa();b.advance();)switch(h=b.Ea(),h){case "rect":var r=b,w=e(Number(f.page));h=w.ha({x:r.V("x1")||0,y:r.V("y1")||0});r=w.ha({x:r.V("x2")||0,y:r.V("y2")||0});h=new n.a(h.x,h.y,r.x,r.y);h.normalize();f.rect={x1:h.x1,y1:h.y1,
x2:h.x2,y2:h.y2};break;case "border":h=b;r={style:h.V("style")||"Solid",width:h.V("width")||1,color:[0,0,0]};for(h.wa();h.advance();)switch(w=h.Ea(),w){case "color":r.color=a(h);break;default:console.warn("unrecognised border child: "+w)}h.Na();f.border=r;break;case "background-color":f.backgroundColor=a(b);break;case "actions":f.actions=db(b,"E X D U Fo Bl PO PC PV PI".split(" "),e);break;case "appearances":h=b;r=re.Ci(f,"appearances");for(h.wa();h.advance();)if(w=h.Ea(),"appearance"===w){w=h.V("name");
var x=re.Ci(r,w);w=h;for(w.wa();w.advance();){var y=w.Ea();switch(y){case "Normal":re.Ci(x,"Normal").data=w.current.textContent;break;default:console.warn("unexpected appearance state: ",y)}}w.Na()}else console.warn("unexpected appearances child: "+w);h.Na();break;case "extra":h=b;r=e;w={};for(h.wa();h.advance();)switch(x=h.Ea(),x){case "font":w.font=le(h,r(1));break;default:console.warn("unrecognised extra child: "+x)}h.Na();h=w;h.font&&(f.font=h.font);break;case "captions":r=b;h={};(w=r.V("Normal"))&&
(h.Normal=w);(w=r.V("Rollover"))&&(h.Rollover=w);(r=r.V("Down"))&&(h.Down=r);f.captions=h;break;default:console.warn("unrecognised widget child: "+h)}b.Na();return f}function ne(a){var b={value:a.V("value")};(a=a.V("display-value"))&&(b.displayValue=a);return b}function ve(a,e){var f=a.V("name"),h={type:a.V("type"),quadding:a.V("quadding")||"Left-justified",maxLen:a.V("max-len")||-1},n=a.V("flags");Object(y.isString)(n)&&(h.flags=n.split(" "));for(a.wa();a.advance();)switch(n=a.Ea(),n){case "actions":h.actions=
db(a,["C","F","K","V"],e);break;case "default-value":n=a;n.wa();n.advance();var r=n.current.textContent;n.Na();h.defaultValue=r;break;case "font":h.font=le(a,e);break;case "options":n=a;r=[];for(n.wa();n.advance();){var w=n.Ea();switch(w){case "option":r.push(ne(n));break;default:console.warn("unrecognised options child: "+w)}}n.Na();h.options=r;break;default:console.warn("unknown field child: "+n)}a.Na();return new b.Annotations.fa.oa(f,h)}function ye(a,b){switch(a.type){case "Tx":return new w.h(a,
b);case "Ch":return a.flags.get("Combo")?new w.c(a,b):new w.d(a,b);case "Btn":return a.flags.get("PushButton")?new w.e(a,b):a.flags.get("Radio")?new w.f(a,b):new w.b(a,b);case "Sig":return new w.g(a,b);default:console.warn("Unrecognised field type: "+a.type)}return null}function ue(a,b){var e={number:a.V("number")};for(a.wa();a.advance();){var f=a.Ea();switch(f){case "actions":e.actions=db(a,["O","C"],b);break;default:console.warn("unrecognised page child: "+f)}}a.Na();return e}b.xf=b.xf||{};var re=
b.xf;re.xN={parse:function(a,b,e,h){var n=[],r={};a.wa();var w=[],x={},y=[];Object(z.a)(function(){if(a.advance()){var e=a.Ea();switch(e){case "calculation-order":w=f(a);break;case "document-actions":x=db(a,["Init","Open"],b);break;case "pages":e=[];for(a.wa();a.advance();){var h=a.Ea();switch(h){case "page":e.push(ue(a,b));break;default:console.warn("unrecognised page child: "+h)}}a.Na();y=e;break;case "field":e=ve(a,b(1));r[e.name]=e;break;case "widget":h=oe(a,b);(e=r[h.fieldName])?(e=ye(e,h),n.push(e)):
console.warn("ignoring widget with no corresponding field data: "+h.fieldName);break;default:console.warn("Unknown element encountered in PDFInfo: "+e)}return!0}return!1},function(){a.Na();e({calculationOrder:w,widgets:n,fields:r,documentActions:x,pages:y,custom:[]})},h)},PV:ve,TV:oe,NV:f}}(window)}}]);}).call(this || window)
