(function(){var E="function"==typeof Object.defineProperties?Object.defineProperty:function(g,f,a){g!=Array.prototype&&g!=Object.prototype&&(g[f]=a.value)},K="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function N(g,f){if(f){var a=K;g=g.split(".");for(var c=0;c<g.length-1;c++){var b=g[c];b in a||(a[b]={});a=a[b]}g=g[g.length-1];c=a[g];f=f(c);f!=c&&null!=f&&E(a,g,{configurable:!0,writable:!0,value:f})}}
N("Array.from",function(g){return g?g:function(f,a,c){a=null!=a?a:function(a){return a};var b=[],d="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];if("function"==typeof d){f=d.call(f);for(var e=0;!(d=f.next()).done;)b.push(a.call(c,d.value,e++))}else for(d=f.length,e=0;e<d;e++)b.push(a.call(c,f[e],e));return b}});
function P(g,f,a){if(null==g)throw new TypeError("The 'this' value for String.prototype."+a+" must not be null or undefined");if(f instanceof RegExp)throw new TypeError("First argument to String.prototype."+a+" must not be a regular expression");return g+""}N("String.prototype.endsWith",function(g){return g?g:function(f,a){var c=P(this,f,"endsWith");f+="";void 0===a&&(a=c.length);a=Math.max(0,Math.min(a|0,c.length));for(var b=f.length;0<b&&0<a;)if(c[--a]!=f[--b])return!1;return 0>=b}});
N("String.prototype.startsWith",function(g){return g?g:function(f,a){var c=P(this,f,"startsWith");f+="";var b=c.length,d=f.length;a=Math.max(0,Math.min(a|0,c.length));for(var e=0;e<d&&a<b;)if(c[a++]!=f[e++])return!1;return e>=d}});
N("String.fromCodePoint",function(g){return g?g:function(f){for(var a="",c=0;c<arguments.length;c++){var b=Number(arguments[c]);if(0>b||1114111<b||b!==Math.floor(b))throw new RangeError("invalid_code_point "+b);65535>=b?a+=String.fromCharCode(b):(b-=65536,a+=String.fromCharCode(b>>>10&1023|55296),a+=String.fromCharCode(b&1023|56320))}return a}});function Q(g){var f=0;return function(){return f<g.length?{done:!1,value:g[f++]}:{done:!0}}}function R(){R=function(){};K.Symbol||(K.Symbol=S)}
var S=function(){var g=0;return function(f){return"jscomp_symbol_"+(f||"")+g++}}();function T(){R();var g=K.Symbol.iterator;g||(g=K.Symbol.iterator=K.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&E(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return U(Q(this))}});T=function(){}}function U(g){T();g={next:g};g[K.Symbol.iterator]=function(){return this};return g}
function V(g,f){T();g instanceof String&&(g+="");var a=0,c={next:function(){if(a<g.length){var b=a++;return{value:f(b,g[b]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c}N("Array.prototype.keys",function(g){return g?g:function(){return V(this,function(f){return f})}});
(function(g){function f(c){if(a[c])return a[c].Db;var b=a[c]={Rg:c,If:!1,Db:{}};g[c].call(b.Db,b,b.Db,f);b.If=!0;return b.Db}var a={};f.Ba=g;f.Dg=a;f.d=function(a,b,d){f.Lf(a,b)||Object.defineProperty(a,b,{enumerable:!0,get:d})};f.r=function(a){"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};f.t=function(a,b){b&1&&(a=f(a));if(b&8||b&4&&"object"===typeof a&&a&&a.ne)return a;var d=Object.create(null);
f.r(d);Object.defineProperty(d,"default",{enumerable:!0,value:a});if(b&2&&"string"!=typeof a)for(var c in a)f.d(d,c,function(b){return a[b]}.bind(null,c));return d};f.n=function(a){var b=a&&a.ne?function(){return a["default"]}:function(){return a};f.d(b,"a",b);return b};f.Lf=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};f.p="/core/";return f(f.lh=1)})([function(g,f){function a(a,d,e,l,t,n){this.Oa=16;this.je=288;this.status=0;this.root=null;this.Ba=0;var r=Array(this.Oa+1),k,f,h,
g=Array(this.Oa+1),u,m=new c,p=Array(this.Oa);var q=Array(this.je);var w=Array(this.Oa+1),J,C;var L=this.root=null;for(f=0;f<r.length;f++)r[f]=0;for(f=0;f<g.length;f++)g[f]=0;for(f=0;f<p.length;f++)p[f]=null;for(f=0;f<q.length;f++)q[f]=0;for(f=0;f<w.length;f++)w[f]=0;var O=256<d?a[256]:this.Oa;var B=a;var z=0;f=d;do r[B[z]]++,z++;while(0<--f);if(r[0]==d)this.root=null,this.status=this.Ba=0;else{for(h=1;h<=this.Oa&&0==r[h];h++);var D=h;n<h&&(n=h);for(f=this.Oa;0!=f&&0==r[f];f--);var M=f;n>f&&(n=f);
for(J=1<<h;h<f;h++,J<<=1)if(0>(J-=r[h])){this.status=2;this.Ba=n;return}if(0>(J-=r[f]))this.status=2,this.Ba=n;else{r[f]+=J;w[1]=h=0;B=r;z=1;for(u=2;0<--f;)w[u++]=h+=B[z++];B=a;f=z=0;do 0!=(h=B[z++])&&(q[w[h]++]=f);while(++f<d);d=w[M];w[0]=f=0;B=q;z=0;q=-1;var y=g[0]=0;u=null;for(C=0;D<=M;D++)for(a=r[D];0<a--;){for(;D>y+g[1+q];){y+=g[1+q];q++;C=(C=M-y)>n?n:C;if((k=1<<(h=D-y))>a+1)for(k-=a+1,u=D;++h<C&&!((k<<=1)<=r[++u]);)k-=r[u];y+h>O&&y<O&&(h=O-y);C=1<<h;g[1+q]=h;u=Array(C);for(k=0;k<C;k++)u[k]=
new c;L=null==L?this.root=new b:L.next=new b;L.next=null;L.list=u;p[q]=u;0<q&&(w[q]=f,m.va=g[q],m.e=16+h,m.t=u,h=(f&(1<<y)-1)>>y-g[q],p[q-1][h].e=m.e,p[q-1][h].va=m.va,p[q-1][h].n=m.n,p[q-1][h].t=m.t)}m.va=D-y;z>=d?m.e=99:B[z]<e?(m.e=256>B[z]?16:15,m.n=B[z++]):(m.e=t[B[z]-e],m.n=l[B[z++]-e]);k=1<<D-y;for(h=f>>y;h<C;h+=k)u[h].e=m.e,u[h].va=m.va,u[h].n=m.n,u[h].t=m.t;for(h=1<<D-1;0!=(f&h);h>>=1)f^=h;for(f^=h;(f&(1<<y)-1)!=w[q];)y-=g[q],q--}this.Ba=g[1];this.status=0!=J&&1!=M?1:0}}}function c(){this.n=
this.va=this.e=0;this.t=null}function b(){this.list=this.next=null}var d=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],e=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],l=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],t=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],n=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],k=[16,17,
18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],p={lc:function(a){this.$f();this.ic=a;this.jc=0}};p.lc.prototype={Od:function(a){for(var b,d=Array(1024),c=[],e=0;e<a&&0<(b=this.Zf(d,0,d.length));)c[c.length]=String.fromCharCode.apply(null,d.slice(0,b)),e+=b;return e?(this.ic=this.ic.slice(this.jc),this.jc=0,c.join("")):""},Vf:function(){return this.ic.length==this.jc?-1:this.ic.charCodeAt(this.jc++)&255},P:function(a){for(;this.$a<a;)this.sb|=this.Vf()<<this.$a,this.$a+=8},U:function(a){return this.sb&
d[a]},O:function(a){this.sb>>=a;this.$a-=a},hc:function(a,b,d){var c,e;if(0==d)return 0;for(e=0;;){this.P(this.ya);var l=this.Na.list[this.U(this.ya)];for(c=l.e;16<c;){if(99==c)return-1;this.O(l.va);c-=16;this.P(c);l=l.t[this.U(c)];c=l.e}this.O(l.va);if(16==c)this.fa&=32767,a[b+e++]=this.Ma[this.fa++]=l.n;else{if(15==c)break;this.P(c);this.la=l.n+this.U(c);this.O(c);this.P(this.rb);l=this.ae.list[this.U(this.rb)];for(c=l.e;16<c;){if(99==c)return-1;this.O(l.va);c-=16;this.P(c);l=l.t[this.U(c)];c=l.e}this.O(l.va);
this.P(c);this.ab=this.fa-l.n-this.U(c);for(this.O(c);0<this.la&&e<d;)this.la--,this.ab&=32767,this.fa&=32767,a[b+e++]=this.Ma[this.fa++]=this.Ma[this.ab++]}if(e==d)return d}this.La=-1;return e},ag:function(a,b,d){var c=this.$a&7;this.O(c);this.P(16);c=this.U(16);this.O(16);this.P(16);if(c!=(~this.sb&65535))return-1;this.O(16);this.la=c;for(c=0;0<this.la&&c<d;)this.la--,this.fa&=32767,this.P(8),a[b+c++]=this.Ma[this.fa++]=this.U(8),this.O(8);0==this.la&&(this.La=-1);return c},Yf:function(b,d,c){if(null==
this.gc){var f,k=Array(288);for(f=0;144>f;f++)k[f]=8;for(;256>f;f++)k[f]=9;for(;280>f;f++)k[f]=7;for(;288>f;f++)k[f]=8;this.Nc=7;f=new a(k,288,257,e,l,this.Nc);if(0!=f.status)return alert("HufBuild error: ".concat(f.status)),-1;this.gc=f.root;this.Nc=f.Ba;for(f=0;30>f;f++)k[f]=5;this.Mc=5;f=new a(k,30,0,t,n,this.Mc);if(1<f.status)return this.gc=null,alert("HufBuild error: ".concat(f.status)),-1;this.Wf=f.root;this.Mc=f.Ba}this.Na=this.gc;this.ae=this.Wf;this.ya=this.Nc;this.rb=this.Mc;return this.hc(b,
d,c)},Xf:function(b,d,c){var f,h,g,m=Array(316);for(f=0;f<m.length;f++)m[f]=0;this.P(5);var p=257+this.U(5);this.O(5);this.P(5);var q=1+this.U(5);this.O(5);this.P(4);f=4+this.U(4);this.O(4);if(286<p||30<q)return-1;for(h=0;h<f;h++)this.P(3),m[k[h]]=this.U(3),this.O(3);for(;19>h;h++)m[k[h]]=0;this.ya=7;h=new a(m,19,19,null,null,this.ya);if(0!=h.status)return-1;this.Na=h.root;this.ya=h.Ba;var v=p+q;for(f=g=0;f<v;){this.P(this.ya);var H=this.Na.list[this.U(this.ya)];h=H.va;this.O(h);h=H.n;if(16>h)m[f++]=
g=h;else if(16==h){this.P(2);h=3+this.U(2);this.O(2);if(f+h>v)return-1;for(;0<h--;)m[f++]=g}else{17==h?(this.P(3),h=3+this.U(3),this.O(3)):(this.P(7),h=11+this.U(7),this.O(7));if(f+h>v)return-1;for(;0<h--;)m[f++]=0;g=0}}this.ya=9;h=new a(m,p,257,e,l,this.ya);0==this.ya&&(h.status=1);if(0!=h.status)return-1;this.Na=h.root;this.ya=h.Ba;for(f=0;f<q;f++)m[f]=m[f+p];this.rb=6;h=new a(m,q,0,t,n,this.rb);this.ae=h.root;this.rb=h.Ba;return 0==this.rb&&257<p||0!=h.status?-1:this.hc(b,d,c)},$f:function(){null==
this.Ma&&(this.Ma=Array(65536));this.$a=this.sb=this.fa=0;this.La=-1;this.fc=!1;this.la=this.ab=0;this.gc=this.Na=null},Zf:function(a,b,d){var c;for(c=0;c<d&&(!this.fc||-1!=this.La);){if(0<this.la){if(0!=this.La)for(;0<this.la&&c<d;)this.la--,this.ab&=32767,this.fa&=32767,a[b+c++]=this.Ma[this.fa++]=this.Ma[this.ab++];else{for(;0<this.la&&c<d;)this.la--,this.fa&=32767,this.P(8),a[b+c++]=this.Ma[this.fa++]=this.U(8),this.O(8);0==this.la&&(this.La=-1)}if(c==d)break}if(-1==this.La){if(this.fc)break;
this.P(1);0!=this.U(1)&&(this.fc=!0);this.O(1);this.P(2);this.La=this.U(2);this.O(2);this.Na=null;this.la=0}switch(this.La){case 0:var e=this.ag(a,b+c,d-c);break;case 1:e=null!=this.Na?this.hc(a,b+c,d-c):this.Yf(a,b+c,d-c);break;case 2:e=null!=this.Na?this.hc(a,b+c,d-c):this.Xf(a,b+c,d-c);break;default:e=-1}if(-1==e)return this.fc?0:-1;c+=e}return c}};p.Rd=function(a){return(new p.lc(a)).Od(4E9)};f.a=p},function(g,f,a){g.Db=a(2)},function(g,f,a){a.r(f);a(3);a(4);g=a(5);a.n(g);a(6)},function(){function g(){throw new TypeError("Invalid attempt to spread non-iterable instance");
}function f(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}function a(a){if(Array.isArray(a)){for(var b=0,d=Array(a.length);b<a.length;b++)d[b]=a[b];return d}}var c=self,b=c.$d;(function(){function a(a){l?l.push(a):setTimeout(a,0)}var e={version:"0.7.2.0",$g:function(a){return void 0===a},Zg:function(a){return null===a},wa:function(a){return null===a||void 0===a},ah:function(a){return null!==a&&void 0!==a}},l=[];c.attachEvent&&c.attachEvent("onload",
function(){if(l){var a=l;l=null;for(var b=0,d=a.length;b<d;b++)a[b]()}});b||(c.$d=b={Za:a,ready:a});for(var t in e)b[t]=e[t]})();Object.na="Object";Object.Pa=null;Object.Gg=function(a){for(var b in a)delete a[b]};Object.Td=function(a,b){return void 0!==a[b]};Object.keys?Object.Bf=function(a){return Object.keys(a).length}:(Object.keys=function(a){var b=[],d;for(d in a)b.push(d);return b},Object.Bf=function(a){var b=0,d;for(d in a)b++;return b});Boolean.na="Boolean";Boolean.parse=function(a){return"true"==
a.toLowerCase()};Number.na="Number";Number.parse=function(a){return a&&a.length?0<=a.indexOf(".")||0<=a.indexOf("e")||a.endsWith("f")||a.endsWith("F")?parseFloat(a):parseInt(a,10):0};Number.prototype.format=function(a){return b.wa(a)||0==a.length||"i"==a?this.toString():this.vd(a,!1)};Number.prototype.Vd=function(a){return b.wa(a)||0==a.length||"i"==a?this.toLocaleString():this.vd(a,!0)};Number.nc=function(a,b,c,t){var d=null;c=a.indexOf(c);0<c&&(d=a.substr(c),a=a.substr(0,c));(c=a.startsWith("-"))&&
(a=a.substr(1));var e=0,l=b[e];if(a.length<l)return d?a+d:a;for(var f=a.length,g="",m=!1;!m;){var r=l,u=f-r;0>u&&(l+=u,r+=u,u=0,m=!0);if(!r)break;u=a.substr(u,r);g=g.length?u+t+g:u;f-=r;e<b.length-1&&(e++,l=b[e])}c&&(g="-".concat(g));return d?g+d:g};Number.prototype.vd=function(a,c){c=c?b.be.bg.Kf:b.be.cg.Kf;var d="",e=-1;1<a.length&&(e=parseInt(a.substr(1)));a=a.charAt(0);switch(a){case "d":case "D":d=parseInt(Math.abs(this)).toString();-1!=e&&(d=d.Yd(e));0>this&&(d="-".concat(d));break;case "x":case "X":d=
parseInt(Math.abs(this)).toString(16);"X"==a&&(d=d.toUpperCase());-1!=e&&(d=d.Yd(e));break;case "e":case "E":d=-1==e?this.toExponential():this.toExponential(e);"E"==a&&(d=d.toUpperCase());break;case "f":case "F":case "n":case "N":-1==e&&(e=c.bh);d=this.toFixed(e).toString();e&&"."!=c.Xd&&(e=d.indexOf("."),d=d.substr(0,e)+c.Xd+d.substr(e+1));if("n"==a||"N"==a)d=Number.nc(d,c.eh,c.Xd,c.dh);break;case "c":case "C":-1==e&&(e=c.Kg);d=Math.abs(this).toFixed(e).toString();e&&"."!=c.Ld&&(e=d.indexOf("."),
d=d.substr(0,e)+c.Ld+d.substr(e+1));d=Number.nc(d,c.Mg,c.Ld,c.Lg);d=0>this?String.format(c.Ng,d):String.format(c.Og,d);break;case "p":case "P":-1==e&&(e=c.fh),d=(100*Math.abs(this)).toFixed(e).toString(),e&&"."!=c.Zd&&(e=d.indexOf("."),d=d.substr(0,e)+c.Zd+d.substr(e+1)),d=Number.nc(d,c.hh,c.Zd,c.gh),d=0>this?String.format(c.ih,d):String.format(c.jh,d)}return d};String.na="String";String.ce="";String.compare=function(a,b,c){c&&(a&&(a=a.toUpperCase()),b&&(b=b.toUpperCase()));a=a||"";b=b||"";return a==
b?0:a<b?-1:1};String.concat=function(){return 2===arguments.length?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,"")};String.prototype.endsWith=function(a){return a.length?a.length>this.length?!1:this.substr(this.length-a.length)==a:!0};String.Ja=function(a,b,c){return 0==String.compare(a,b,c)};String.gd=function(a,c,l){String.hd||(String.hd=/(\{[^\}^\{]+\})/g);return a.replace(String.hd,function(a,d){a=c[parseInt(d.substr(1))+1];if(b.wa(a))return"";if(a.format){var e=null,f=d.indexOf(":");
0<f&&(e=d.substring(f+1,d.length-1));return l?a.Vd(e):a.format(e)}return l?a.toLocaleString():a.toString()})};String.format=function(a){return String.gd(a,arguments,!1)};String.yf=function(a){for(var b="0",d=1;d<a;d++)b+="0";return b};String.Gf=function(a){return!a||!a.length};String.Vd=function(a){return String.gd(a,arguments,!0)};String.prototype.Yd=function(a){return this.length<a?String.yf(a-this.length)+this:this};String.prototype.remove=function(a,b){return!b||a+b>this.length?this.substr(0,
a):this.substr(0,a)+this.substr(a+b)};String.prototype.startsWith=function(a){return a.length?a.length>this.length?!1:this.substr(0,a.length)==a:!0};String.prototype.trim||(String.prototype.trim=function(){return this.Sf().Tf()});String.prototype.Sf=function(){return this.replace(/\s*$/,"")};String.prototype.Tf=function(){return this.replace(/^\s*/,"")};Array.na="Array";Array.Lb=[b.Ib];Array.prototype.add=function(a){this.push(a)};Object.defineProperty(Array.prototype,"add",{enumerable:!1,writable:!0});
Array.prototype.addRange=function(a){this.push.apply(this,a)};Object.defineProperty(Array.prototype,"addRange",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,"aggregate",{enumerable:!1,writable:!0});Array.prototype.clear=function(){this.length=0};Object.defineProperty(Array.prototype,"clear",{enumerable:!1,writable:!0});Array.prototype.clone=function(){return 1===this.length?[this[0]]:Array.apply(void 0,a(this)||f(this)||g())};Object.defineProperty(Array.prototype,"clone",{enumerable:!1,
writable:!0});Array.prototype.contains=function(a){return 0<=this.indexOf(a)};Object.defineProperty(Array.prototype,"contains",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,"dequeue",{enumerable:!1,writable:!0});Array.prototype.enqueue=function(a){this.sf=!0;this.push(a)};Object.defineProperty(Array.prototype,"enqueue",{enumerable:!1,writable:!0});Array.prototype.Z=function(){return this.length?this[this.sf?0:this.length-1]:null};Object.defineProperty(Array.prototype,"peek",{enumerable:!1,
writable:!0});Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,d=0;d<c;d++)if(d in this&&!a.call(b,this[d],d,this))return!1;return!0},Object.defineProperty(Array.prototype,"every",{enumerable:!1,writable:!0}));Object.defineProperty(Array.prototype,"extract",{enumerable:!1,writable:!0});Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,d=[],e=0;e<c;e++)if(e in this){var f=this[e];a.call(b,f,e,this)&&d.push(f)}return d},Object.defineProperty(Array.prototype,
"filter",{enumerable:!1,writable:!0}));Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=this.length,d=0;d<c;d++)d in this&&a.call(b,this[d],d,this)},Object.defineProperty(Array.prototype,"forEach",{enumerable:!1,writable:!0}));Array.prototype.Ya=function(){return new b.Gb(this)};Object.defineProperty(Array.prototype,"getEnumerator",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,"groupBy",{enumerable:!1,writable:!0});Array.prototype.index=function(a,b){for(var c=
this.length,d={},e=0;e<c;e++)if(e in this){var f=a.call(b,this[e],e);String.Gf(f)||(d[f]=this[e])}return d};Object.defineProperty(Array.prototype,"index",{enumerable:!1,writable:!0});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length;if(c)for(b=b||0;b<c;b++)if(this[b]===a)return b;return-1},Object.defineProperty(Array.prototype,"indexOf",{enumerable:!1,writable:!0}));Object.defineProperty(Array.prototype,"insert",{enumerable:!1,writable:!0});Object.defineProperty(Array.prototype,
"insertRange",{enumerable:!1,writable:!0});Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,d=Array(c),e=0;e<c;e++)e in this&&(d[e]=a.call(b,this[e],e,this));return d},Object.defineProperty(Array.prototype,"map",{enumerable:!1,writable:!0}));Array.prototype.remove=function(a){a=this.indexOf(a);return 0<=a?(this.splice(a,1),!0):!1};Object.defineProperty(Array.prototype,"remove",{enumerable:!1,writable:!0});Array.prototype.Jc=function(a){this.splice(a,1)};Object.defineProperty(Array.prototype,
"removeAt",{enumerable:!1,writable:!0});Array.prototype.removeRange=function(a,b){return this.splice(a,b)};Object.defineProperty(Array.prototype,"removeRange",{enumerable:!1,writable:!0});Array.prototype.some||(Array.prototype.some=function(a,b){for(var c=this.length,d=0;d<c;d++)if(d in this&&a.call(b,this[d],d,this))return!0;return!1},Object.defineProperty(Array.prototype,"some",{enumerable:!1,writable:!0}));Array.Rf=function(a){return Array.prototype.slice.call(a)};RegExp.na="RegExp";RegExp.parse=
function(a){if(a.startsWith("/")){var b=a.lastIndexOf("/");if(1<b)return new RegExp(a.substring(1,b),a.substr(b+1))}return null};Error.na="Error";Error.prototype.Mf=function(){if(!(b.wa(this.stack)||b.wa(this.fileName)||b.wa(this.lineNumber))){for(var a=this.stack.split("\n"),c=a[0],l="".concat(this.fileName,":").concat(this.lineNumber);!b.wa(c)&&-1===c.indexOf(l);)a.shift(),c=a[0];c=a[1];isNullOrUndefined(c)||(c=c.match(/@(.*):(\d+)$/),b.wa(c)||(a.shift(),this.stack=a.join("\n"),this.fileName=c[1],
this.lineNumber=parseInt(c[2])))}};Error.Ig=function(a,b,c){a=Error(a);if(b)for(var d in b)a[d]=b[d];c&&(a.Sg=c);a.Mf();return a};c.M=Function;c.M.na="Type";c.Tc=function(a){this.na=a};c.Tc.prototype={oe:!0,getName:function(){return this.na}};c.M.Nf=function(){c.mc||(c.mc={});c.Xc||(c.Xc=[]);if(!c.mc.trn){for(var a=self,b=["trn"],l=0;l<b.length;l++){var f=b[l],g=a[f];g||(a[f]=g=new c.Tc(b.slice(0,l+1).join(".")),0==l&&c.Xc.add(g));a=g}c.mc.trn=a}};c.M.prototype.ca=function(a,b,c){this.prototype.constructor=
this;this.na=a;this.Uc=!0;this.Pa=b||Object;b&&(this.Kb=!0);if(c){this.Lb=[];for(var d=2;d<arguments.length;d++)c=arguments[d],this.Lb.add(c)}};c.M.prototype.Ka=function(a){this.na=a;this.Wc=!0};c.M.prototype.Kc=function(){if(this.Kb){var a=this.Pa;a.Kb&&a.Kc();for(var b in a.prototype){var c=a.prototype[b];this.prototype[b]||(this.prototype[b]=c)}delete this.Kb}};c.M.prototype.Of||(c.M.prototype.Of=c.M.prototype.Kc);c.M.prototype.Ef=function(a){this.Kb&&this.Kc();this.Pa.apply(a)};c.M.prototype.Sd=
function(a){return b.wa(a)?!1:this==Object||a instanceof this?!0:this.Ff(c.M.Af(a))};c.M.prototype.Ff=function(a){if(this==Object||this==a)return!0;if(this.Uc)for(a=a.Pa;a;){if(this==a)return!0;a=a.Pa}else if(this.Wc){var b=a.Lb;if(b&&b.contains(this))return!0;for(a=a.Pa;a;){if((b=a.Lb)&&b.contains(this))return!0;a=a.Pa}}return!1};c.M.Ug=function(a){return 1==a.Uc};c.M.Vg=function(a){return 1==a.me};c.M.Wg=function(a){return 1==a.me&&1==a.Vc};c.M.Xg=function(a){return 1==a.Wc};c.M.Yg=function(a){return 1==
a.oe};c.M.Eg=function(a,b){return b.Sd(a)};c.M.mh=function(a,b){return b.Sd(a)?a:null};c.M.Af=function(a){var b=null;try{b=a.constructor}catch(l){}b&&b.na||(b=Object);return b};b.kc=function(){};b.kc.ca("Enum");b.kc.parse=function(a,b){var c=a.prototype;if(a.Vc){a=b.split("|");b=0;for(var d=!0,e=a.length-1;0<=e;e--){var f=a[e].trim(),g=!1;for(h in c)if(h===f){b|=c[h];g=!0;break}if(!g){d=!1;break}}if(d)return b}else for(var h in c)if(h===b)return c[h];throw"Invalid Enumeration Value";};b.kc.lg=function(a){var b=
this.prototype;if(this.Vc&&0!==a){var c=[];for(d in b)b[d]&a&&(c.length&&c.add(" | "),c.add(d));if(!c.length)throw"Invalid Enumeration Value";return c.join("")}for(var d in b)if(b[d]===a)return d;throw"Invalid Enumeration Value";};b.$=function(){};b.$.ca("Delegate");b.$.empty=function(){};b.$.te=function(a,b,c){for(var d=0;d<a.length;d+=2)if(a[d]===b&&a[d+1]===c)return!0;return!1};b.$.oc=function(a){function c(){if(2==a.length)return a[1].apply(a[0],arguments);for(var c=a.clone(),d=0;d<c.length;d+=
2)b.$.te(a,c[d],c[d+1])&&c[d+1].apply(c[d],arguments);return null}c.Aa=a;return c};b.$.create=function(a,c){return a?b.$.oc([a,c]):c};b.$.Hg=function(a,c){return a?c?b.$.oc((a.Aa?a.Aa:[null,a]).concat(c.Aa?c.Aa:[null,c])):a.Aa?a:b.$.create(null,a):c.Aa?c:b.$.create(null,c)};b.$.remove=function(a,c){if(!a||a===c)return null;if(!c)return a;var d=a.Aa,e=null;c.Aa&&(e=c.Aa[0],c=c.Aa[1]);for(var f=0;f<d.length;f+=2)if(d[f]===e&&d[f+1]===c){if(2==d.length)return null;d.splice(f,2);return b.$.oc(d)}return a};
b.$.Jg=function(a,b,c){c=c||"__".concat((new Date).valueOf());self[c]=b?a:function(){try{delete self[c]}catch(t){self[c]=void 0}a.apply(void 0,arguments)};return c};b.$.Pg=function(a){delete self[a]};b.$.Fg=function(a){self[a]=b.$.empty};b.tb=function(){};b.tb.prototype={Wd:null,reset:null};b.tb.Ya=function(a){return a?a.Ya?a.Ya():new b.Gb(a):null};b.tb.Ka("IEnumerator");b.Ib=function(){};b.Ib.prototype={Ya:null};b.Ib.Ka("IEnumerable");b.Gb=function(a){this.Yc=a;this.Fa=-1;this.current=null};b.Gb.prototype=
{Wd:function(){this.Fa++;this.current=this.Yc[this.Fa];return this.Fa<this.Yc.length},reset:function(){this.Fa=-1;this.current=null}};b.Gb.ca("ArrayEnumerator",null,b.tb);b.Pc=function(){};b.Pc.prototype={wf:null};b.Pc.Ka("IDisposable");b.Rc=function(a){this.Cc=b.wa(a)?[]:[a]};b.Rc.prototype={append:function(a){b.wa(a)||this.Cc.add(a);return this},clear:function(){this.Cc=[]},toString:function(a){return this.Cc.join(a||"")}};b.Rc.ca("StringBuilder");b.Hb=function(){};b.Hb.ca("EventArgs");b.Hb.ce=
new b.Hb;c.XMLHttpRequest||(c.XMLHttpRequest=function(){for(var a=["Msxml2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(l){}return null});b.Oc=function(){b.Oc.Ef(this);this.cancel=!1};b.Oc.ca("CancelEventArgs",b.Hb);b.ke=function(a,b){this.first=a;this.second=b};b.ke.ca("Tuple");b.ma=function(){this.Bb=null};b.ma.prototype={};b.ma.Bc=[];b.ma.lf={wf:function(){b.ma.Bc.pop()}};b.ma.kh=function(a){b.ma.Bc.push(a);return b.ma.lf};b.ma.re=function(a){var c=
b.ma.Bc,d=c.length;if(d){a=a||[];for(var f=0;f<d;f++){var g=c[f];a.contains(g)||a.push(g)}return a}return null};b.ma.hf=function(a){for(var b=0,c=a.length;b<c;b++)a[b].Tg()};b.ma.ca("Observable");b.Qc=function(a){this.Ga=a||[];this.Bb=null};b.Qc.prototype={add:function(a){this.Ga.push(a);this.bc()},clear:function(){this.Ga.clear();this.bc()},contains:function(a){return this.Ga.contains(a)},Ya:function(){this.Bb=b.ma.re(this.Bb);return this.Ga.Ya()},indexOf:function(a){return this.Ga.indexOf(a)},remove:function(a){return this.Ga.remove(a)?
(this.bc(),!0):!1},Jc:function(a){this.Ga.Jc(a);this.bc()},Rf:function(){return this.Ga},bc:function(){var a=this.Bb;a&&(this.Bb=null,b.ma.hf(a))}};b.Qc.ca("ObservableCollection",null,b.Ib);b.de=function(){};b.de.Ka("IApplication");b.ee=function(){};b.ee.Ka("IContainer");b.he=function(){};b.he.Ka("IObjectFactory");b.fe=function(){};b.fe.Ka("IEventManager");b.ge=function(){};b.ge.Ka("IInitializable")},function(){(function(g){function f(a){this.depth=this.index=0;this.J=a;this.location={start:0,cc:1,
dc:1,end:a.length,empty:!0};this.Eb=[this.location];this.Hc=!1;"?"===this.J.charAt(1)&&this.Qd();this.location.empty=!1}g.Jb=g.Jb?g.Jb:{};g.Jb.Uf=function(a){if(a)return a.replace(/&[^;]*;/g,function(a){switch(a.charAt(1)){case "q":return'"';case "a":return"&";case "l":return"<";case "g":return">";case "#":return"x"===a.charAt(2)?String.fromCharCode(parseInt(a.substring(3,a.length-1),16)):String.fromCharCode(parseInt(a.substring(2,a.length-1),10))}return a})};f.prototype={advance:function(){this.Ia=
null;this.Qd();var a=this.location.start;++a;this.location.empty=!1;if("/"!==this.J.charAt(a))return this.location.empty="/"===this.J.charAt(this.J.indexOf(">",a)-1),!0;this.location.end=!0;return!1},Ud:function(){var a=this.location.start+1,c=this.J.indexOf(">",a);this.location.empty&&--c;a=this.J.substring(a,c);this.Ia={};c=a.indexOf(" ");if(-1!==c){this.Nd=a.substring(0,c);a=a.slice(c);a=a.split('"');c=a.length-1;for(var b=0;b<c;++b){var d=a[b],e=a[++b];this.Ia[d.substring(1,d.length-1)]=e}}else this.Nd=
a},Qd:function(){if(this.Hc)this.Hc=!1,this.location.start=this.J.indexOf("<",this.location.start+1);else{var a=this.location.cc;if(!this.location.empty)for(var c=this.location.dc;0<c;)a=this.J.indexOf("<",a),"/"===this.J.charAt(++a)?--c:(a=this.J.indexOf(">",a),"/"!==this.J.charAt(a-1)&&++c);this.location.start=this.J.indexOf("<",a)}this.location.cc=this.location.start+1;this.location.dc=1},mark:function(){this.J.mark&&this.J.mark(this.location.start)},L:function(){null!==this.Ia&&"undefined"!==
typeof this.Ia||this.Ud();return this.Nd},G:function(){++this.depth;this.location={start:this.location.start};this.Eb[this.Eb.length]=this.location;this.Hc=!0},F:function(){--this.depth;this.Ia=null;var a=this.location.cc,c=this.location.dc,b=this.location.empty,d=this.location.end;this.Eb.pop();this.location=this.Eb[this.Eb.length-1];this.location.cc=a;this.location.dc=d?0:b?c:c+1},T:function(){return this.location.empty?!0:"/"===this.J.charAt(this.J.indexOf("<",this.location.start+1)+1)},A:function(a){null!==
this.Ia&&"undefined"!==typeof this.Ia||this.Ud();return g.Jb.Uf(this.Ia[a])}};g.le=f})(self)},function(){function g(f){"@babel/helpers - typeof";g="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return g(f)}(function(){function f(a,c){this.o=[];this.s=[];a&&this.I(a,c)}self.M.Nf();String.fromCodePoint||function(){function a(){var a=[],c=-1,f=
arguments.length;if(!f)return"";for(var g="";++c<f;){var k=Number(arguments[c]);if(!isFinite(k)||0>k||1114111<k||d(k)!==k)throw RangeError("Invalid code point: ".concat(k));if(65535>=k)a.push(k);else{k-=65536;var p=(k>>10)+55296;k=k%1024+56320;a.push(p,k)}if(c+1===f||16384<a.length)g+=b.apply(void 0,a),a.length=0}return g}var c=function(){try{var a={},b=Object.defineProperty;var c=b(a,a,a)&&b}catch(n){}return c}(),b=String.fromCharCode,d=Math.floor;c?c(String,"fromCodePoint",{value:a,configurable:!0,
writable:!0}):String.fromCodePoint=a}();Array.prototype.Ja&&console.warn("Overriding existing Array.prototype.equals. Possible causes: New API defines the method, there's a framework conflict or you've got double inclusions in your code.");Array.prototype.Ja=function(a){if(!a||this.length!==a.length)return!1;for(var c=0,b=this.length;c<b;c++)if(this[c]instanceof Array&&a[c]instanceof Array){if(!this[c].Ja(a[c]))return!1}else if(this[c]!==a[c])return!1;return!0};Object.defineProperty(Array.prototype,
"equals",{enumerable:!1,writable:!0});f.prototype={v:function(a){this.o=this.o.concat(a.o);this.s=this.s.concat(a.s)},I:function(a,c){this.o.push(a);a=g(c);this.s.push("object"===a?c:"undefined"===a?null:[c])},Ja:function(a){return this.o.Ja(a.o)&&this.s.Ja(a.s)},save:function(){this.o.push(trn.b.Se);this.s.push(null)},restore:function(){this.I(trn.b.Re,null)}};trn.b=function(a,c,b,d){this.done=!1;this.pd=2E3;this.Ta={};this.Va=0;this.N=[];this.Ub=[];this.ia=[];this.ia.add({});this.c=a;this.td=this.Fb("Width");
this.sd=this.Fb("Height");this.N.push(trn.Ra.Df(this.td,this.sd));this.ha=!1;this.od=c;this.Tb=b;this.jf=-1<navigator.userAgent.indexOf("Android")&&-1===navigator.userAgent.indexOf("Chrome")&&-1===navigator.userAgent.indexOf("Firefox");this.o=[];this.s=[];this.c.G();this.c.advance();this.Gc=d;a=this.c.L();trn.b.i(a,"FixedPage.Resources")&&(this.c.G(),this.c.advance(),this.Ad(),this.c.F());this.Sa=!1};trn.b.i=function(a,c){var b=trn.b.vf;return a===c?!0:a===b+c};trn.b.Md=function(a){return trn.b.xf(a)};
trn.b.xf=function(a){var c=3,b=Math.abs(a);.5>b&&(c=5E-4>b?5E-7>b?9:7:5);c=Math.pow(10,c);a=Math.round(a*c)/c;return a.toString()};trn.b.D=function(a,c){if(!a)throw Error(c);};trn.b.Qg=function(a){return(new trn.b(a,!1)).Ye()};trn.b.prototype={ef:function(){return this.uc()},pc:function(a,c){var b=this.Xe(),d=this.c.L();if(trn.b.i(d,"Path"))var e=this.sc();else trn.b.i(d,"Canvas")?e=this.Qb():trn.b.i(d,"Glyphs")?e=this.rc():(e=null,trn.b.D(!1,"Invalid Element ".concat(d)));e.pb(b);if(e.Hf()){b=this.ef();
d=this.fb();b.mtx=[d.V,d.W,d.X,d.Y,d.da,d.ea];if(a){a={operators:a.o,data:a.s};var f=this.c.A("RenderTransform");if(null!=f){var g=new trn.H;g.aa(f);f=new trn.H;f.vc(d);f.Qa(g);d=f}a.mtx=[d.V,d.W,d.X,d.Y,d.da,d.ea]}this.I(trn.b.Ve,[b,{x1:e.l,y1:e.m,x2:e.l+e.C,y2:e.m+e.B},c,a]);this.ud=!0}else this.ha=!1},Qb:function(){var a=new trn.ga;this.ba();var c=this.c.A("RenderTransform");if(null!=c){var b=new trn.H;b.aa(c);this.R(b)}c=this.c.A("Clip");null!=c&&(a=this.Da(c));c=null;if(!this.c.T()){for(this.c.G();this.c.advance();)b=
this.c.L(),trn.b.i(b,"Canvas.Clip")?(trn.b.D(!this.c.T(),"Canvas.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),this.R(b),a.pb(this.Da(this.u("Figures"))),b=b.gb(),this.R(b)),this.c.F()):trn.b.i(b,"Path")?null!=c?c.Lc(this.sc()):c=this.sc():trn.b.i(b,"Glyphs")?null!=c?c.Lc(this.rc()):c=this.rc():trn.b.i(b,"Canvas")&&(null!=c?c.Lc(this.Qb()):c=this.Qb());this.c.F()}null!=c&&a.pb(c);this.ra();return a},nf:function(){var a=this.xa("trn:BlendMode",
"source-over");a=this.ha?"source-over":a;var c=this.Dc();c||(this.save(),this.ba());var b=null,d=this.c.A("OpacityMask");null!=d&&(console.warn("Uh oh OpacityMask Resource!"),b=this.Ea(d));if(!this.c.T()){for(this.c.G();this.c.advance();)if(d=this.c.L(),trn.b.i(d,"Canvas.Resources"))this.c.T()?trn.b.D(!1,"Canvas.Resources must contain ResourceDictionary element"):(this.c.G(),this.c.advance(),this.Ad(),this.c.F());else if(trn.b.i(d,"Canvas.Clip"))trn.b.D(!this.c.T(),"Canvas.Clip: Must contain PathGeometry element"),
this.c.G(),this.c.advance()&&(c||(this.save(),c=!0,this.ba()),d=new trn.H,d.aa(this.u("Transform")),this.v(this.R(d)),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),this.ac(this.u("Figures")),d=d.gb(),this.v(this.R(d))),this.c.F();else if(trn.b.i(d,"Canvas.OpacityMask"))this.ha||(this.c.G(),this.c.advance(),b=this.eb(trn.b.oa,new f(trn.b.Nb)),this.c.F());else if(trn.b.i(d,"Path")||trn.b.i(d,"Glyphs")||trn.b.i(d,"Canvas")||trn.b.i(d,"trn:Glyphs")){if(null!=b||"source-over"!==
a){this.Cb();this.c.F();this.ha=!0;this.pc(b,a);return}this.Sa=!1;break}this.Sa&&this.c.F()}this.Sa&&this.Cb();this.ha=!1},Cb:function(){this.restore();this.ra()},Fb:function(a){a=this.c.A(a);trn.b.D(null!=a,"".concat(this.c.L(),": ").concat(a," is not defined"));return parseFloat(a)},sa:function(a,c){a=this.c.A(a);return null!=a?parseFloat(a):c},u:function(a){a=this.c.A(a);trn.b.D(null!=a,"".concat(this.c.L(),": ").concat(a," is not defined"));return a},xa:function(a,c){a=this.c.A(a);return null!=
a?a:c},Pd:function(){var a=this.c.A("x:Key");trn.b.D(null!=a,"Key must be defined for elements in a resource dictionary");return a},Dc:function(){0===this.Va&&this.c.mark();var a=!1,c=this.sa("Opacity",1);1>c&&(a||(a=!0,this.save(),this.ba()),this.v(this.cb(c)));c=this.c.A("RenderTransform");null!=c&&(a||(a=!0,this.save(),this.ba()),this.qf(c));c=this.c.A("Clip");null!=c&&(a||(this.save(),this.ba()),this.ac(c),a=!0);return a},ac:function(a){var c=!0;a&&"F"===a[0]&&(c=!1);this.Cd(c?"evenodd":"nonzero");
this.gf(this.Da(a));this.yd(a);this.o.push(trn.b.xe);this.s.push(c?["evenodd"]:[])},mf:function(a){var c=[];for(a=self.$d.tb.Ya(a.split(";"));a.Wd();){var b=a.current,d=new trn.Fa;b=b.split(",");if(1<=b.length){if(0<b[0].length){var e=b[0].split(")");if(2<=e.length){var f=e[0].substr(1).split(":");d.Vb=parseInt(f[0]);d.xc=parseInt(f[1])}d.Yb=parseInt(e[e.length-1]);d.Ab=!0}2<=b.length&&(0<b[1].length&&(d.wc=parseFloat(b[1]),d.zc=!0),3<=b.length&&(0<b[2].length&&(d.Zb=parseFloat(b[2])),4<=b.length&&
0<b[3].length&&(d.$b=parseFloat(b[3]))))}c.add(d)}return c},ff:function(){var a=this.u("UnicodeString"),c="",b=0;for(2<=a.length&&"{"===a.charAt(0)&&"}"===a.charAt(1)&&(a=a.substr(2));b<a.length;){var d=a.charCodeAt(b);if(9==d)c+=String.fromCharCode(10),b++;else if(128>d)c+=String.fromCharCode(d),b++;else if(191<d)if(224>d){var e=a.charCodeAt(b+1);c+=String.fromCharCode((d&31)<<6|e&63);b+=2}else if(240>d){e=a.charCodeAt(b+1);var f=a.charCodeAt(b+2);c+=String.fromCharCode((d&15)<<12|(e&63)<<6|f&63);
b+=3}else e=a.charCodeAt(b+1),f=a.charCodeAt(b+2),c4=a.charCodeAt(b+3),c+=String.fromCodePoint((d&7)<<18|(e&63)<<12|(f&63)<<6|c4&63),b+=4;else console.warn("Invalid UTF-8 character")}return c},rc:function(){var a=new trn.ga,c=this.c.A("Clip");null!=c&&(a=this.Da(c));return a},tc:function(a,c){return this.jf&&1===a.length?c===trn.b.ad?trn.b.De:c===trn.b.qc?trn.b.qc:trn.b.Ee:c},Sc:function(a){return 0===Object.keys(a).length&&a.constructor===Object},xd:function(a){var c=this.xa("trn:BlendMode","source-over");
c=this.ha?"source-over":c;var b="source-over"!=c&&!this.Tb,d=this.Dc();this.Tb&&this.Bd(c);var e=this.Fb("OriginX"),l=this.Fb("OriginY"),g=this.u("FontUri");this.xb[g]=null;var n=this.Fb("FontRenderingEmSize"),k=this.mf(this.xa("Indices",""));if(200>n){var p=n/200;d||(this.ba(),this.save(),d=!0);var h=new trn.H;h.vb(p,0,0,p,e,l);n=200;l=0;this.o.push(trn.b.Pb);this.s.push(h.Rb())}var q=0;e=new f;var m=this.ff(),r=0,u=0,w=n/100,A="",F=null;a=(h=this.c.A("Stroke"))?trn.b.qc:a?trn.b.ad:trn.b.Ce;e.I(trn.b.Te,
0);for(var G={},v,H=0;H<k.length;){var x=k[H],I=m.charCodeAt(q);I=x.Vb+(55296<=I&&57344>I?1:0);if(r!==x.Zb||u!==x.$b)A&&(e.I(this.tc(v,a),[A,r?r*w:0,l-u*w]),e.I(trn.b.cd,[A])),r=x.Zb,u=x.$b,A="";x.Ab&&(G[A.length]=m.substr(q,x.Vb));x.zc?(this.Sc(G)||e.I(trn.b.fd,[G]),v=A+(x.Ab?String.fromCharCode(x.Yb+57344):m.substr(q,I)),e.I(this.tc(v,a),[v,r?r*w:0,l-u*w]),A&&e.I(trn.b.cd,[A]),e.I(trn.b.ue,[x.wc*w]),G={},A=""):A+=x.Ab?String.fromCharCode(x.Yb+57344):m.substr(q,I);H+=x.xc;q+=I}if(A||q<m.length)this.Sc(G)||
e.I(trn.b.fd,[G]),v=A+m.substr(q,m.length-q),e.I(this.tc(v,a),[v,0,0]);l=v=null;r=this.c.A("Fill");q=!1;null!=r&&(this.Sb(r)?v=this.Ea(r,trn.b.oa,e):(q=!0,v=this.ub(r,trn.b.oa,e)));k=!1;null!=h&&(this.Sb(h)?F=this.Ea(h,trn.b.Ca,e):(k=!0,F=this.ub(h,trn.b.Ca,e)));r=this.c.A("OpacityMask");null!=r&&(console.warn("Uh oh OpacityMask Resource!"),l=this.Ea(r));if(!this.c.T()&&!a){for(this.c.G();this.c.advance();)a=this.c.L(),trn.b.i(a,"Glyphs.Clip")?(trn.b.D(!this.c.T(),"Canvas.Clip: Must contain PathGeometry element"),
this.c.G(),this.c.advance()&&(d||(d=!0,this.save(),this.ba()),h=new trn.H,h.aa(this.u("Transform")),this.o.push(trn.b.Pb),this.s.push(h.Rb()),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),a=this.u("Figures"),this.ac(a),h=h.gb(),this.o.push(trn.b.Pb),this.s.push(h.Rb())),this.c.F()):trn.b.i(a,"Glyphs.Fill")?(this.c.G(),this.c.advance(),v=this.eb(trn.b.oa,e),this.c.F()):trn.b.i(a,"Glyphs.OpacityMask")&&!this.ha&&(this.c.G(),this.c.advance(),l=this.eb(trn.b.oa,new f(trn.b.Nb)),
this.c.F());this.c.F()}if(null==l||b)"otf"===g.substr(g.indexOf(".")+1)?(g=g.substr(0,g.length-4),g=parseInt(g.substr(7))):g=parseInt(g.substr(35,8),16),g="f".concat(this.Gc,"-").concat(g),Object.Td(this.Ta,g)?10>this.Ta[g].length&&(this.Ta[g]+=m.substr(0,10-this.Ta[g].length)):this.Ta[g]=m.substr(0,10),this.tf("".concat(trn.b.Md(n),"px ").concat(g)),null!==v&&(q||(v=new f(trn.b.oa,"#000000"),v.v(e)),this.Ec(v,e)),null!=F&&(n=this.sa("StrokeThickness",1),r=this.c.A("RenderTransform"),m=new trn.H,
null!=r&&m.aa(r),this.Fc(n/(p*m.Xa())),this.Dd(this.ld(this.xa("StrokeStartLineCap","Flat"))),this.Ed(this.xa("StrokeLineJoin","miter").toLowerCase()),this.Fd(this.sa("StrokeMiterLimit",10)),k||(F=new f(trn.b.Ca,"#000000"),F.v(e)),this.Gd(F,e));d&&(this.restore(),this.ra());if(null!=l||b)this.ha=!0,this.pc(l,c);this.ha=!1},kd:function(){var a=[];this.c.G();trn.b.D(this.c.advance(),"Gradient brushes must contain GradientStops");for(this.c.G();this.c.advance();){var c=this.u("Color"),b=this.u("Offset");
a.push(b);a.push(this.jd(c))}this.c.F();this.c.F();return a},af:function(a,c,b){var d=this.c.A("Transform"),e=new f;e.save();this.ba();null!=d&&(b.aa(d),e.v(this.R(b)));b=this.sa("Opacity",1);1>b&&e.v(this.cb(b));d=this.u("StartPoint").split(",");b=parseFloat(d[0]);d=parseFloat(d[1]);var l=this.u("EndPoint").split(",");b={type:trn.b.Me,x0:b,y0:d,x1:parseFloat(l[0]),y1:parseFloat(l[1]),stops:this.kd()};e.I(a,[b]);e.v(c);e.restore();this.ra();return e},cf:function(a,c,b){var d=this.c.A("Transform"),
e=new f,l=this.u("RadiusX"),g=this.u("RadiusY"),n=this.u("GradientOrigin"),k=this.u("Center");e.save();this.ba();var p=parseFloat(l),h=parseFloat(g);trn.b.D(0<p&&0<h,"Invalid radius value");var q=k.split(",");k=parseFloat(q[0]);q=parseFloat(q[1]);var m=n.split(",");n=parseFloat(m[0]);m=parseFloat(m[1]);if(null!=d||l!==g)null!=d&&b.aa(d),d=h/p,m/=d,q/=d,g=new trn.H,g.vb(1,0,0,d,0,0),b.Qa(g),e.v(this.R(b));b=this.sa("Opacity",1);1>b&&e.v(this.cb(b));l={type:trn.b.Pe,x0:n,y0:m,x1:k,y1:q,r:l,stops:this.kd()};
e.I(a,[l]);e.v(c);e.restore();this.ra();return e},uf:function(){trn.b.D(!this.Xb,"Incorrect custom glyph start");this.o.push(trn.b.ze);this.s.push(null);this.Xb=!0},We:function(){trn.b.D(this.Xb,"Incorrect custom glyph end");this.o.push(trn.b.Ae);this.s.push(null);this.Xb=!1},v:f.prototype.v,I:f.prototype.I,Gd:function(a,c){var b=this.N.Z();a.Ja(b.ob)?c?this.v(c):this.I(trn.b.Ob,null):(a.o[0]===trn.b.Ca&&(b.ob=a),this.v(a))},Ec:function(a,c){var b=this.N.Z();a.Ja(b.ib)?this.v(c):(a.o[0]===trn.b.oa&&
(b.ib=a),this.v(a))},Bd:function(a){var c=this.N.Z();a!==c.zb&&(c.zb=a,this.I(trn.b.He,[a]))},cb:function(a){var c=this.N.Z();c.Ua*=a;return new f(trn.b.Ge,[c.Ua])},Cd:function(a){var c=this.N.Z();a!==c.hb&&(c.hb=a)},Fc:function(a){var c=this.N.Z();a!==c.mb&&(c.mb=a,this.o.push(trn.b.Le),this.s.push([a,this.fb().Xa()]))},Dd:function(a){var c=this.N.Z();a!==c.kb&&(c.kb=a,this.o.push(trn.b.Je),this.s.push([a]))},Ed:function(a){var c=this.N.Z();a!==c.lb&&(c.lb=a,this.o.push(trn.b.Ke),this.s.push([a]))},
Fd:function(a){var c=this.N.Z();a!==c.nb&&(c.nb=a,this.o.push(trn.b.Ne),this.s.push([a]))},tf:function(a){var c=this.N.Z();a!==c.jb&&(c.jb=a,this.o.push(trn.b.Fe),this.s.push([a]))},R:function(a){this.N.Z().za.Qa(a);return new f(trn.b.Pb,a.Rb())},fb:function(){return this.N.Z().za},Xe:function(){return this.N.Z().ta},gf:function(a){this.N.Z().ta.pb(a)},ba:function(a){a=a?this.N.Z().Jf():this.N.Z().clone();this.N.push(a);this.ia.add({})},ra:function(){this.N.pop();for(var a=Object.keys(this.ia[this.ia.length-
1]),c=0;c<a;++c)this.I(trn.b.Be);this.ia.Jc(this.ia.length-1)},Ze:function(a,c,b){var d=new f,e=this.c.A("Transform");d.save();this.ba();var l=this.u("Viewbox"),g=new trn.ga;g.Za(l);l=this.u("Viewport");var n=new trn.ga;n.Za(l);if(null!=e||g!==n){l=n.C/g.C;var k=n.B/g.B,p=n.l-g.l*l;g=n.m-g.m*k;null!=e&&b.aa(e);e=new trn.H;e.vb(l,0,0,k,p,g);b.Qa(e);d.v(this.R(b))}b=this.sa("Opacity",1);1>b&&d.v(this.cb(b));b=this.xa("TileMode","None");e=this.u("ImageSource");this.xb[e]=null;d.I(a,[{type:trn.b.Ie,name:"i".concat(this.Gc,
"-").concat(parseInt(e.split("/")[2])),tm:"None"===b?"no-repeat":"repeat"}]);d.v(c);d.restore();this.ra();return d},$e:function(){var a=new f,c=this.c.A("Transform");a.save();this.ba();var b=this.u("Viewbox"),d=new trn.ga;d.Za(b);b=this.u("Viewport");var e=new trn.ga;e.Za(b);if(null!=c||d!==e){b=e.C/d.C;var l=e.B/d.B,g=e.l-d.l*b;d=e.m-d.m*l;e=new trn.H;null!=c&&e.aa(c);c=new trn.H;c.vb(b,0,0,l,g,d);e.Qa(c);a.v(this.R(e))}c=this.sa("Opacity",1);1>c&&a.v(this.cb(c));this.xa("TileMode","None");c=this.u("ImageSource");
this.xb[c]=null;c="i".concat(this.Gc,"-").concat(parseInt(c.split("/")[2]));this.od?a.I(trn.b.$c,[c,this.fb().Xa()]):a.I(trn.b.$c,[c]);a.restore();this.ra();return a},qf:function(a){if(null!=a){var c=new trn.H;c.aa(a);this.v(this.R(c))}},j:function(a){for(var c,b=c=a.K,d=a.ja,e=d[c];" "!==e&&","!==e;)++c,e=d[c];b=d.substring(b,c);++c;a.K=c;return parseFloat(b)},Da:function(a){var c=" ",b=new trn.Mb(a,0,null,0),d=new trn.ga,e=!0;d.initData(0,0,0,0);if(b.K<b.ja.length)for(;" "===b.ja.charAt(b.K);)b.K++;
for(;b.K<a.length;){if("A"<=b.ja.charAt(b.K)&&"Z">=b.ja.charAt(b.K)||"a"<=b.ja.charAt(b.K)&&"z">=b.ja.charAt(b.K))c=b.ja.charAt(b.K),b.K++;else switch("a">c&&("H"!==c&&(b.g=0),"V"!==c&&(b.f=0)),c){case "m":case "M":b.f+=this.j(b);b.g+=this.j(b);e?(d.initData(b.f,b.g,b.f,b.g),e=!1):d.ka(b.f,b.g);b.S=!1;break;case "l":case "L":b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;case "c":case "C":var f=this.j(b)+b.f;var g=this.j(b)+b.g;d.ka(f,g);b.S=!0;b.pa=this.j(b)+b.f;b.qa=this.j(b)+b.g;d.ka(b.pa,
b.qa);b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);break;case "q":case "Q":f=this.j(b)+b.f;g=this.j(b)+b.g;d.ka(f,g);b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;case "s":case "S":b.S||(b.pa=b.f,b.qa=b.g);f=2*b.f-b.pa;g=2*b.g-b.qa;d.ka(f,g);b.S=!0;b.pa=this.j(b)+b.f;b.qa=this.j(b)+b.g;d.ka(b.pa,b.qa);b.f+=this.j(b);b.g+=this.j(b);d.ka(b.f,b.g);break;case "h":case "H":b.f+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;case "v":case "V":b.g+=this.j(b);d.ka(b.f,b.g);b.S=!1;break;default:this.j(b),
b.S=!1}for(;" "===a.charAt(b.K);)++b.K}return d.Cf(this.fb())},sc:function(){var a=null;this.ba();var c=this.c.A("RenderTransform");if(null!=c){var b=new trn.H;b.aa(c);this.R(b)}var d=this.c.A("Stroke"),e=this.sa("StrokeThickness",1);c=this.c.A("Clip");null!=c&&(a=this.Da(c));c=this.c.A("Data");if(!this.c.T()){for(this.c.G();this.c.advance();)if(b=this.c.L(),trn.b.i(b,"Path.Data")&&!this.c.T()){this.c.G();this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),this.R(b),trn.b.D(trn.b.i(this.c.L(),
"PathGeometry"),"Path.Data must contain PathGeometry"),c=this.u("Figures"));this.c.F();break}else trn.b.i(b,"Path.Clip")?(trn.b.D(!this.c.T(),"Path.Clip: Must contain PathGeometry element"),this.c.G(),this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),this.R(b),a=this.Da(this.u("Figures")),b=b.gb(),this.R(b)),this.c.F()):trn.b.i(b,"Path.Stroke")&&(d=!0);this.c.F()}null!=a?a.pb(this.Da(c)):a=this.Da(c);this.ra();d&&a.Rd(e);return a},wb:function(a,c,b){a.S=!1;if(null==a.ua)this.o.push(trn.b.bd),
this.s.push([a.f,a.g]);else for(var d=a.ua.length,e=a.f-c,f=a.g-b,g=f/e,n=Math.sqrt(e*e+f*f);1E-10<n;){var k=a.ua[a.Wb%d]-a.yb,p=k>n;p&&(a.yb+=n,k=n);if(e){var h=Math.sqrt(k*k/(1+g*g));0>e&&(h=-h);c+=h;b+=g*h}else b+=0<f?k:-k;this.o.push(a.Wb%2?trn.b.dd:trn.b.bd);this.s.push([c,b]);n-=k;p||(++a.Wb,a.yb=0)}},Zc:function(a,c,b,d,e){a.S=!0;if(null==a.ua)this.o.push(trn.b.we),this.s.push([d,e,a.pa,a.qa,a.f,a.g]);else{var f=this.fb().Xa();f*=(Math.abs(a.f-c)+Math.abs(a.g-b))/5;var g=a.f,n=a.g;a.f=c;a.g=
b;f=1/parseInt(f);for(var k=0;1>=k;k+=f){var p=1-k,h=a.f,q=a.g;a.f=p*p*p*c+3*p*p*k*d+3*p*k*k*a.pa+k*k*k*g;a.g=p*p*p*b+3*p*p*k*e+3*p*k*k*a.qa+k*k*k*n;this.wb(a,h,q)}}},se:function(a){if(null==a.ua)this.o.push(trn.b.ye),this.s.push(null);else{var c=a.f,b=a.g;a.f=a.qd;a.g=a.rd;this.wb(a,c,b)}},kf:function(a){a.qd=a.f;a.rd=a.g;this.o.push(trn.b.dd);this.s.push([a.f,a.g]);a.S=!1;a.Wb=a.yc;a.yb=a.Ha},pf:function(a,c){var b=a.f,d=a.g;"a">c&&("H"!==c&&(a.g=0),"V"!==c&&(a.f=0));switch(c){case "m":case "M":a.f+=
this.j(a);a.g+=this.j(a);this.kf(a);break;case "l":case "L":a.f+=this.j(a);a.g+=this.j(a);this.wb(a,b,d);break;case "c":case "C":c=this.j(a)+a.f;var e=this.j(a)+a.g;a.pa=this.j(a)+a.f;a.qa=this.j(a)+a.g;a.f+=this.j(a);a.g+=this.j(a);this.Zc(a,b,d,c,e);break;case "q":case "Q":c=this.j(a)+a.f;e=this.j(a)+a.g;a.f+=this.j(a);a.g+=this.j(a);this.I(trn.b.Oe,[c,e,a.f,a.g]);a.S=!1;break;case "s":case "S":a.S||(a.pa=a.f,a.qa=a.g);c=2*a.f-a.pa;e=2*a.g-a.qa;a.S=!0;a.pa=this.j(a)+a.f;a.qa=this.j(a)+a.g;a.f+=
this.j(a);a.g+=this.j(a);this.Zc(a,b,d,c,e);break;case "h":case "H":a.f+=this.j(a);this.wb(a,b,d);a.S=!1;break;case "v":case "V":a.g+=this.j(a);this.wb(a,b,d);a.S=!1;break;default:this.j(a),a.S=!1}},ld:function(a){if("Flat"===a)return"butt";if("Square"===a)return"square";if("Round"===a||"Triangle"===a)return"round";trn.b.D(!1,"Invalid line cap ".concat(a));return""},yd:function(a){this.zd(a,null,0)},zd:function(a,c,b){var d=" ";c=new trn.Mb(a,0,c,b);b=c.ja.charAt(c.K);this.o.push(trn.b.ve);this.s.push(null);
if(c.K<c.ja.length)for(;" "===b;)c.K++,b=c.ja.charAt(c.K);for(;c.K<a.length;)for("A"<=b&&"Z">=b||"a"<=b&&"z">=b?(d=b,"z"!==b&&"Z"!==b||this.se(c),c.K++):this.pf(c,d),b=c.ja.charAt(c.K);" "===b;)++c.K,b=c.ja.charAt(c.K)},save:f.prototype.save,restore:f.prototype.restore,rf:function(){var a=this.xa("trn:BlendMode","source-over");a=this.ha?"source-over":a;var c="source-over"!=a&&!this.Tb,b=this.c.A("Data"),d=!0;b&&"F"===b[0]&&(d=!1);var e=new f(trn.b.Nb,d?["evenodd"]:null),g=!1,t=this.Dc(),n=null,k=
this.c.A("Fill");null!=k&&(n=this.Sb(k)?this.Ea(k,trn.b.oa,e):this.ub(k,trn.b.oa,e));this.Tb&&this.Bd(a);var p=k=null,h=this.sa("StrokeThickness",1),q=this.c.A("Stroke");null!=q&&(this.Fc(h),k=this.Sb(q)?this.Ea(q,trn.b.Ca,new f(trn.b.Ob)):this.ub(q,trn.b.Ca,new f(trn.b.Ob)));q=null;var m=this.c.A("OpacityMask");null!=m&&(console.warn("Uh oh OpacityMask Resource!"),q=this.Ea(m));m=null;if(!this.c.T()){for(this.c.G();this.c.advance();){var r=this.c.L();trn.b.i(r,"Path.Clip")?(trn.b.D(!this.c.T(),"Path.Clip: Must contain PathGeometry element"),
this.c.G(),this.c.advance()&&(t||(t=!0,this.save(),this.ba()),m=new trn.H,m.aa(this.u("Transform")),this.v(this.R(m)),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Clip must contain PathGeometry"),r=this.u("Figures"),this.ac(r),m=m.gb()),this.c.F()):trn.b.i(r,"Path.Data")&&!this.c.T()?(this.c.G(),this.c.advance()&&(b=new trn.H,b.aa(this.u("Transform")),null!=m?m.Qa(b):m=b,this.v(this.R(m)),trn.b.D(trn.b.i(this.c.L(),"PathGeometry"),"Path.Data must contain PathGeometry"),b=this.u("Figures")),this.c.F()):
trn.b.i(r,"Path.Fill")?(this.c.G(),this.c.advance(),null!=q||c||"ImageBrush"!==this.c.L()?n=this.eb(trn.b.oa,e):(g=!0,this.v(this.$e())),this.c.F()):trn.b.i(r,"Path.OpacityMask")?this.ha||(this.c.G(),this.c.advance(),q=this.eb(trn.b.oa,e),this.c.F()):trn.b.i(r,"Path.Stroke")&&(this.c.G(),this.c.advance(),k=this.eb(trn.b.Ca,new f(trn.b.Ob),h),this.c.F())}this.c.F()}if(null==q&&!c&&!g){trn.b.D(null!=b,"Paths must have Data defined");g=this.c.A("StrokeDashArray");if(null!=g)for(g=g.split(" "),p=Array(g.length),
m=0;m<g.length;++m)if(p[m]=parseFloat(g[m])*h,!p[m]||.02>p[m])p[m]=.02;this.Cd(d?"evenodd":"nonzero");d=this.sa("StrokeDashOffset",0);null!=p&&null!=n&&(this.yd(b),null!=n&&this.Ec(n,e),n=null);this.zd(b,p,d);null!=n&&this.Ec(n,e);null!=k&&(this.Dd(this.ld(this.xa("StrokeStartLineCap","Flat"))),this.Ed(this.xa("StrokeLineJoin","miter").toLowerCase()),this.Fd(this.sa("StrokeMiterLimit",10)),this.Gd(k))}t&&(this.restore(),this.ra());if(null!=q||c)this.ha=!0,this.pc(q,a);this.ha=!1},jd:function(a){var c=
1,b=[255,255,255,255];if("#"===a.charAt(0)){if(7===a.length)return a;trn.b.D(9===a.length,"Color ".concat(a," is invalid in a XOD file"));c=a.substr(1,2);var d=a.substr(3,2);var e=a.substr(5,2);a=a.substr(7,2);c=parseInt(c,16)/255;b[0]=parseInt(d,16);b[1]=parseInt(e,16);b[2]=parseInt(a,16)}else"s"===a.charAt(0)?(d=a.split("#")[1].split(","),3<d.length?(c=parseFloat(d[0]),e=255*parseFloat(d[1]),b[0]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[2]),b[1]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[3])):
(e=255*parseFloat(d[0]),b[0]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[1]),b[1]=parseInt(0>e?0:255<e?255:e),e=255*parseFloat(d[2])),b[2]=parseInt(0>e?0:255<e?255:e)):trn.b.D(!1,"Invalid color for a XOD file");return"rgba(".concat(b[0],",").concat(b[1],",").concat(b[2],",").concat(trn.b.Md(c),")")},df:function(a,c){return this.ub(this.u("Color"),a,c)},ub:function(a,c,b){a=new f(c,this.jd(a));a.v(b);return a},uc:function(){var a=this.Va,c=this.o,b=this.s;this.o=[];this.s=[];this.Va=this.c.depth;
this.ba(!0);if(!this.c.T()||!trn.b.i(this.c.L(),"Canvas"))for(this.Sa=!1;this.Ac(););this.ra();var d={operators:this.o,data:this.s};this.Va=a;this.o=c;this.s=b;return d},md:function(a,c,b,d){var e=new f,g=this.u("Viewbox"),t=new trn.ga;t.Za(g);g=this.u("Viewport");var n=new trn.ga;n.Za(g);g=this.c.A("Transform");e.save();this.ba();if(!this.c.T()){for(this.c.G();this.c.advance();){var k=this.c.L();if(trn.b.i(k,"VisualBrush.Visual")){this.c.G();trn.b.D(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element");
this.ba(!0);this.N.Z().za=new trn.H;var p=this.Qb();this.ra();this.c.F()}}this.c.F()}if("undefined"!==typeof p&&0!==p.B&&0!==p.C){k=n.l-t.l;var h=n.m-t.m;t.pb(p);n=t;n.l+=k;n.m+=h}if(0===t.C||0===t.B)return e=new f(a,"rgba(0,0,0,0)"),e.v(c),e;if(null!=g||t!==n)k=n.C/t.C,p=n.B/t.B,h=n.l-t.l*k,n=n.m-t.m*p,null!=g&&b.aa(g),g=new trn.H,g.vb(k,0,0,p,h,n),b.Qa(g),e.v(this.R(b));n=this.fb().Xa();g=Math.min(t.C,t.B);k=this.sa("Opacity",1);1>k&&e.v(this.cb(k));p=this.xa("TileMode","None");h={};k=this.c.A("Visual");
null!=k&&(k=this.Ea(k),h.operators={operators:k.o,data:k.s});if(!this.c.T()){for(this.c.G();this.c.advance();)k=this.c.L(),trn.b.i(k,"VisualBrush.Visual")&&(this.c.G(),trn.b.D(this.c.advance(),"VisualBrush.Visual must contain Canvas, Path or Glyphs element"),h.operators=this.uc(),this.c.F());this.c.F()}h.type=trn.b.Ue;h.tm="None"===p?"no-repeat":"repeat";a===trn.b.Ca&&(h.strokeAdjust=d/b.Xa());if(t.l||t.m)h.x=t.l,h.y=t.m;h.w=t.C;h.h=t.B;h.minwh=g;h.scale=n;e.I(a,[h]);e.v(c);e.restore();this.ra();
return e},Sb:function(a){return"{"===a.charAt(0)},Ea:function(a){var c=a.indexOf("StaticResource");trn.b.D(0<c,"Invalid resource reference: ".concat(a));c+=15;a=a.substr(c,a.length-1-c);c=null;for(var b=this.ia.length-1;0<=b;--b)if(Object.Td(this.ia[b],a)){c=this.ia[b][a];break}trn.b.D(null!=c,"Dictionary key ".concat(a," does not exist."));return new f(trn.b.Qe,[a])},Ac:function(){if(this.Sa){if(this.c.depth===this.Va)return trn.b.i(this.c.L(),"Canvas")&&this.Cb(),!1;var a=this.c.advance();if(!a){this.c.F();
if(this.Ub.Z()===this.c.depth)return this.Ub.pop(),this.We(),!0;if(this.c.depth===this.Va)return trn.b.i(this.c.L(),"Canvas")&&this.Cb(),!1;this.Cb();return!0}}this.Sa=!0;a=this.c.L();trn.b.i(a,"Canvas")?this.nf():trn.b.i(a,"Path")?this.rf():trn.b.i(a,"Glyphs")?this.xd(!1):trn.b.i(a,"trn:Glyphs")&&(this.c.T()||this.Ub.push(this.c.depth),this.xd(!0),this.c.T()||(this.c.G(),this.uf()));return!0},qe:function(){var a=trn.b.oa,c=new f(trn.b.Nb);a=this.md(a,c,new trn.H);c=this.Pd();this.ia[this.ia.length-
1][c]=a;this.I(trn.b.ed,[c,a.o,a.s])},pe:function(a){a=this.uc();var c=this.Pd();this.ia[this.ia.length-1][c]=a;this.I(trn.b.ed,[c,a.operators,a.data])},eb:function(a,c,b){var d=new trn.H,e=this.c.L();if(trn.b.i(e,"VisualBrush"))var f=this.md(a,c,d,b);else trn.b.i(e,"ImageBrush")?f=this.Ze(a,c,d):trn.b.i(e,"LinearGradientBrush")?f=this.af(a,c,d):trn.b.i(e,"RadialGradientBrush")?f=this.cf(a,c,d):trn.b.i(e,"SolidColorBrush")?f=this.df(a,c):trn.b.D(!1,"Invalid Brush Type: ".concat(e)),"undefined"!==
typeof b&&(this.R(d),this.Fc(b/d.Xa()),this.R(d.gb()));return f},Ad:function(){var a=this.c.L();if(trn.b.i(a,"ResourceDictionary")&&!this.c.T()){for(this.c.G();this.c.advance();)a=this.c.L(),trn.b.i(a,"VisualBrush")?this.qe():trn.b.i(a,"Canvas")?this.pe():trn.b.D(!1,"Resource type is invalid: ".concat(a));this.c.F()}},Ye:function(){for(var a="";!this.done;)a+=this.qb();return a},qb:function(){this.ud=!1;for(this.xb={};this.o.length<this.pd&&!this.ud&&this.Ac(););this.Ac()||(this.done=!0);var a={operators:this.o,
data:this.s};this.o=[];this.s=[];return a},zf:function(){var a=[],c=this.xb,b;for(b in c)a.add(b.substr(1));return a},done:!1,Sa:!1,ha:!1,td:0,sd:0,od:!1,pd:0,Ta:null,xb:null,Va:0,ia:null,N:null,c:null,Ub:null,Xb:!1};trn.Fa=function(){this.zc=this.Ab=!1;this.Vb=this.xc=1;this.wc=this.Zb=this.$b=this.Yb=0};trn.Fa.prototype={Ab:!1,zc:!1,Vb:0,xc:0,Yb:0,wc:0,Zb:0,$b:0};trn.Ra=function(){};trn.Ra.Df=function(a,c){var b=new trn.Ra;b.ob="black";b.ib="black";b.hb="nonzero";b.Ua=1;b.zb="source-over";b.mb=
1;b.kb="butt";b.lb="miter";b.nb=10;b.jb="10px sans-serif";b.za=new trn.H;b.ta=new trn.ga;b.ta.initData(0,0,a,c);return b};trn.Ra.prototype={clone:function(){var a=new trn.Ra;a.ob=this.ob;a.ib=this.ib;a.hb=this.hb;a.Ua=this.Ua;a.zb=this.zb;a.mb=this.mb;a.kb=this.kb;a.lb=this.lb;a.nb=this.nb;a.jb=this.jb;a.za=new trn.H;a.za.vc(this.za);a.ta=new trn.ga;a.ta.initData(this.ta.l,this.ta.m,this.ta.C,this.ta.B);return a},Jf:function(){var a=new trn.Ra;a.ob="black";a.ib="black";a.hb="nonzero";a.Ua=1;a.zb=
"source-over";a.mb=1;a.kb="butt";a.lb="miter";a.nb=10;a.jb="10px sans-serif";a.za=new trn.H;a.za.vc(this.za);a.ta=new trn.ga;return a},ob:null,ib:null,hb:null,Ua:0,mb:0,kb:null,lb:null,nb:0,jb:null,za:null,ta:null};trn.bb=function(a,c){this.x=a;this.y=c};trn.bb.prototype={x:0,y:0};trn.ga=function(){this.m=this.l=-1E6;this.C=this.B=2E6};trn.ga.prototype={initData:function(a,c,b,d){this.l=a;this.m=c;this.C=b;this.B=d},Hf:function(){return 0<this.C&&0<this.B},Za:function(a){a=a.split(",");trn.b.D(4===
a.length,"Rectangles should contain 4 numbers");this.l=parseFloat(a[0]);this.m=parseFloat(a[1]);this.C=parseFloat(a[2]);this.B=parseFloat(a[3])},Cf:function(a){if(a.nd())return this;var c=new trn.bb(this.l,this.m),b=new trn.bb(this.l,this.m+this.B),d=new trn.bb(this.l+this.C,this.m),e=new trn.bb(this.l+this.C,this.m+this.B);a.ec(c);a.ec(b);a.ec(d);a.ec(e);a=Math.min(c.x,b.x,d.x,e.x);var f=Math.min(c.y,b.y,d.y,e.y),g=new trn.ga;g.initData(a,f,Math.max(c.x,b.x,d.x,e.x)-a,Math.max(c.y,b.y,d.y,e.y)-f);
return g},ka:function(a,c){a<this.l?(this.C+=this.l-a,this.l=a):a>this.l+this.C&&(this.C=a-this.l);c<this.m?(this.B+=this.m-c,this.m=c):c>this.m+this.B&&(this.B=c-this.m)},Lc:function(a){this.ka(a.l,a.m);this.ka(a.l+a.C,a.m+a.B)},pb:function(a){var c=this.l;var b=this.l+this.C;var d=this.m;var e=this.m+this.B;var f=a.l;var g=a.l+a.C;var n=a.m;a=a.m+a.B;b<f||g<c||e<n||a<d?this.l=this.C=this.m=this.B=0:(this.l=c<f?f:c,this.C=(b<g?b:g)-this.l,this.m=d<n?n:d,this.B=(e<a?e:a)-this.m,this.C&&this.B||(this.l=
this.C=this.m=this.B=0))},Rd:function(a){this.l-=a;this.m-=a;this.C+=2*a;this.B+=2*a},l:0,m:0,C:0,B:0};trn.H=function(){};trn.H.prototype={V:1,W:0,X:0,Y:1,da:0,ea:0,aa:function(a){var c=[1,0,0,1,0,0];a=a.split(",");for(var b=0;b<a.length&&6>b;++b)c[b]=parseFloat(a[b]);this.V=c[0];this.W=c[1];this.X=c[2];this.Y=c[3];this.da=c[4];this.ea=c[5]},vb:function(a,c,b,d,e,f){this.V=a;this.W=c;this.X=b;this.Y=d;this.da=e;this.ea=f},vc:function(a){this.V=a.V;this.W=a.W;this.X=a.X;this.Y=a.Y;this.da=a.da;this.ea=
a.ea},Qa:function(a){var c=this.V,b=this.W,d=this.X,e=this.Y;this.V=a.V*c+a.W*d;this.W=a.V*b+a.W*e;this.X=a.X*c+a.Y*d;this.Y=a.X*b+a.Y*e;this.da=a.da*c+a.ea*d+this.da;this.ea=a.da*b+a.ea*e+this.ea},gb:function(){var a=new trn.H,c=this.V*this.Y-this.W*this.X;if(!c)return a;a.V=this.Y/c;a.X=-this.X/c;a.da=(this.X*this.ea-this.da*this.Y)/c;a.W=-this.W/c;a.Y=this.V/c;a.ea=-(this.V*this.ea-this.da*this.W)/c;return a},ec:function(a){var c=a.x*this.W+a.y*this.Y+this.ea;a.x=a.x*this.V+a.y*this.X+this.da;
a.y=c},Xa:function(){var a=.707106781*this.V+.707106781*this.W,c=.707106781*this.X+.707106781*this.Y;return Math.sqrt(a*a+c*c)},nd:function(){return 1!==this.V||this.W||this.X||1!==this.Y||this.da||this.ea?!1:!0},Rb:function(){return this.bf()},bf:function(){return this.nd()?null:[this.V,this.W,this.X,this.Y,this.da,this.ea]}};trn.Mb=function(a,c,b,d){this.ja=a;this.K=c;this.f=this.g=0;this.S=!1;this.ua=b;if(null!=this.ua){for(c=a=0;c<this.ua.length;++c)a+=this.ua[c];this.Ha=d%a;0>this.Ha&&(this.Ha+=
a);for(c=this.yc=0;this.Ha>this.ua[c];++c)this.Ha-=this.ua[c],++this.yc}};trn.Mb.prototype={ja:null,K:0,ua:null,Wb:0,yb:0,yc:0,Ha:0,f:0,g:0,qd:0,rd:0,S:!1,pa:0,qa:0};trn.wd=function(){};trn.wd.prototype={};trn.b.ca("trn.Converter");trn.Fa.ca("trn._index");trn.Ra.ca("trn._gState");trn.bb.ca("trn.Point");trn.ga.ca("trn._rect");trn.H.ca("trn._matrix2D");trn.Mb.ca("trn._abbrGeomItr");trn.wd.ca("trn._pageInfo");trn.b.mg="http://schemas.microsoft.com/xps/2005/06/resourcedictionary-key";trn.b.sg="http://schemas.openxps.org/oxps/v1.0/resourcedictionary-key";
trn.b.yg="http://schemas.microsoft.com/winfx/2006/xaml";trn.b.vf="http://schemas.microsoft.com/xps/2005/06";trn.b.zg="http://schemas.microsoft.com/winfx/2006/xaml/presentation";trn.b.tg="http://schemas.openxps.org/oxps/v1.0";trn.b.Bg="http://schemas.microsoft.com/xps/2005/06/documentstructure";trn.b.rg="http://schemas.openxps.org/oxps/v1.0/documentstructure";trn.b.wg="http://schemas.openxmlformats.org/package/2006/relationships";trn.b.dg="http://schemas.openxmlformats.org/package/2006/content-types";
trn.b.ng="http://schemas.openxmlformats.org/markup-compatibility/2006";trn.b.eg="http://schemas.openxmlformats.org/package/2006/metadata/core-properties";trn.b.fg="http://purl.org/dc/elements/1.1/";trn.b.gg="http://purl.org/dc/terms/";trn.b.Ag="http://www.w3.org/XML/1998/namespace";trn.b.xg="clr-namespace:PDFTron.SilverDox.Internal;assembly=SilverDox";trn.b.Cg="http://schemas.microsoft.com/xps/2005/06/restricted-font";trn.b.ug="http://schemas.openxps.org/oxps/v1.0/restricted-font";trn.b.og="application/vnd.ms-package.obfuscated-opentype";
trn.b.vg="http://www.pdftron.com/silverdox/2010/09";trn.b.Se=0;trn.b.Re=1;trn.b.Pb=2;trn.b.kg=3;trn.b.Le=4;trn.b.Je=5;trn.b.Ca=6;trn.b.oa=7;trn.b.Ge=8;trn.b.ed=9;trn.b.Be=10;trn.b.ue=11;trn.b.Qe=12;trn.b.ve=13;trn.b.ye=14;trn.b.Nb=15;trn.b.Ob=16;trn.b.xe=17;trn.b.dd=18;trn.b.bd=19;trn.b.Oe=20;trn.b.we=21;trn.b.Fe=22;trn.b.Ce=23;trn.b.cd=24;trn.b.Te=25;trn.b.Ne=26;trn.b.Ke=27;trn.b.$c=28;trn.b.jg=29;trn.b.ig=30;trn.b.Ee=31;trn.b.ze=32;trn.b.Ae=33;trn.b.He=34;trn.b.fd=35;trn.b.Ve=36;trn.b.hg=37;trn.b.ad=
38;trn.b.De=39;trn.b.qc=40;trn.b.Ue=1;trn.b.Me=2;trn.b.Pe=3;trn.b.Ie=4;trn.b.pg="S r t T w c s f a L R P A b z F X C M l q B n x m W i j I Z d D e xw cgb cge g bO tm".split(" ");trn.b.qg="S r t T w c s f a L R P A b z F X C M l q B n xc m W i j I Z d D e xcw cgb cge g bO tm".split(" ")})()},function(g,f,a){var c=a(0);(function(a){function b(a){this.J="";this.Qf=new c.a.lc(a);this.Ic();this.start=0}a.trn.b||(a.trn=trn);b.prototype={Id:102400,mark:function(a){var c=a-this.start;c>b.prototype.Id&&(this.J=
this.J.slice(c),this.start=a)},indexOf:function(a,b){b-=this.start;do var c=this.J.indexOf(a,b);while(-1===c&&this.Ic());return c+this.start},charAt:function(a){a-=this.start;a>=this.J.length&&this.Ic();return this.J.charAt(a)},substring:function(a,b){a-=this.start;b-=this.start;return this.J.substring(a,b)},Ic:function(){var a=this.Qf.Od(b.prototype.Id);return a.length?(this.J+=a,!0):!1}};a.qb=function(){if(a.Wa.done)return a.postMessage({command:"done"}),a.Wa=null,!1;var b=a.Wa.qb();a.postMessage({command:"nextChunk",
resources:a.Wa.zf(),dataString:b});return!0};var e=function(){var a=navigator.userAgent.toLowerCase();return(a=/(msie) ([\w.]+)/.exec(a)||/(trident)(?:.*? rv:([\w.]+)|)/.exec(a))?parseInt(a[2],10):a}();a.Jd=function(){if(9===e)for(;a.qb(););else setTimeout(function(){a.Wa&&a.qb()&&a.Jd()},0)};a.ie=b;a.Hd=!1;a.onmessage=function(b){switch(b.data.command){case "data":var c=new a.le(new a.ie(b.data.dataString));a.Wa=new a.trn.b(c,a.Hd,a.Pf,b.data.docId);a.Kd&&a.Jd();break;case "nextChunk":a.Kd||a.Wa&&
a.qb();break;case "cancel":a.Wa=null;a.postMessage({command:"done"});break;case "options":a.Hd=b.data.imageScaling;a.Pf=b.data.specialBlendSupported;a.Kd=b.data.continueWithoutPrompt;break;default:throw Error("Unknown message command ".concat(b.data.command));}}})(self)}]);}).call(this || window)
